tell application "Microsoft Outlook"

    set newMessage to make new outgoing message with properties {subject:"CSL Resale Advantage – Your Custom Referral Link", content:"Hey Alec,<br><br>Check out the new website here: https://www.centerstreetlending.com/resale-advantage<br>Thanks for joining the information session this week on the new CSL Resale Advantage program! <br><br>Below is your custom link to send to your borrowers:<br><br>https://www.centerstreetlending.com/resale-advantage?rep=aralph<br><br>When a borrower uses your link, your information is automatically pushed through the form and marked in the system. As a backup, we can also always confirm you are the referral by communicating directly with Innovate Realty. <br><br>If you'd like to make a custom email signature with your URL, feel free to add it into your Signature block to get evergreen marketing for your referral link. <br><br>*Example: Find out how CSL borrowers are getting 1% exclusive listing fees on their next sale. [Learn more here.]*<br><br>If you have any questions about the program or need additional info, please reach out directly to Suzanne or Paul:<br><br>Suzanne Seini  <br>Innovate Realty  <br>suzanne@innovaterealty.com  <br><br><br>*— OR —*<br><br><br>Paul Hanson  <br>phanson@byebyehouse.com  <br><br><br>Thanks,<br><br>Greg"}
    make new to recipient at newMessage with properties {email address:{address:"aralph@centerstreetlending.com"}}
    open newMessage
    

    set newMessage to make new outgoing message with properties {subject:"CSL Resale Advantage – Your Custom Referral Link", content:"Hey Allyssa,<br><br>Check out the new website here: https://www.centerstreetlending.com/resale-advantage<br>Thanks for joining the information session this week on the new CSL Resale Advantage program! <br><br>Below is your custom link to send to your borrowers:<br><br>https://www.centerstreetlending.com/resale-advantage?rep=amichaelson<br><br>When a borrower uses your link, your information is automatically pushed through the form and marked in the system. As a backup, we can also always confirm you are the referral by communicating directly with Innovate Realty. <br><br>If you'd like to make a custom email signature with your URL, feel free to add it into your Signature block to get evergreen marketing for your referral link. <br><br>*Example: Find out how CSL borrowers are getting 1% exclusive listing fees on their next sale. [Learn more here.]*<br><br>If you have any questions about the program or need additional info, please reach out directly to Suzanne or Paul:<br><br>Suzanne Seini  <br>Innovate Realty  <br>suzanne@innovaterealty.com  <br><br><br>*— OR —*<br><br><br>Paul Hanson  <br>phanson@byebyehouse.com  <br><br><br>Thanks,<br><br>Greg"}
    make new to recipient at newMessage with properties {email address:{address:"amichaelson@centerstreetlending.com"}}
    open newMessage
    

    set newMessage to make new outgoing message with properties {subject:"CSL Resale Advantage – Your Custom Referral Link", content:"Hey Angelica,<br><br>Check out the new website here: https://www.centerstreetlending.com/resale-advantage<br>Thanks for joining the information session this week on the new CSL Resale Advantage program! <br><br>Below is your custom link to send to your borrowers:<br><br>https://www.centerstreetlending.com/resale-advantage?rep=anaranjo<br><br>When a borrower uses your link, your information is automatically pushed through the form and marked in the system. As a backup, we can also always confirm you are the referral by communicating directly with Innovate Realty. <br><br>If you'd like to make a custom email signature with your URL, feel free to add it into your Signature block to get evergreen marketing for your referral link. <br><br>*Example: Find out how CSL borrowers are getting 1% exclusive listing fees on their next sale. [Learn more here.]*<br><br>If you have any questions about the program or need additional info, please reach out directly to Suzanne or Paul:<br><br>Suzanne Seini  <br>Innovate Realty  <br>suzanne@innovaterealty.com  <br><br><br>*— OR —*<br><br><br>Paul Hanson  <br>phanson@byebyehouse.com  <br><br><br>Thanks,<br><br>Greg"}
    make new to recipient at newMessage with properties {email address:{address:"anaranjo@centerstreetlending.com"}}
    open newMessage
    

    set newMessage to make new outgoing message with properties {subject:"CSL Resale Advantage – Your Custom Referral Link", content:"Hey Christine,<br><br>Check out the new website here: https://www.centerstreetlending.com/resale-advantage<br>Thanks for joining the information session this week on the new CSL Resale Advantage program! <br><br>Below is your custom link to send to your borrowers:<br><br>https://www.centerstreetlending.com/resale-advantage?rep=cflores<br><br>When a borrower uses your link, your information is automatically pushed through the form and marked in the system. As a backup, we can also always confirm you are the referral by communicating directly with Innovate Realty. <br><br>If you'd like to make a custom email signature with your URL, feel free to add it into your Signature block to get evergreen marketing for your referral link. <br><br>*Example: Find out how CSL borrowers are getting 1% exclusive listing fees on their next sale. [Learn more here.]*<br><br>If you have any questions about the program or need additional info, please reach out directly to Suzanne or Paul:<br><br>Suzanne Seini  <br>Innovate Realty  <br>suzanne@innovaterealty.com  <br><br><br>*— OR —*<br><br><br>Paul Hanson  <br>phanson@byebyehouse.com  <br><br><br>Thanks,<br><br>Greg"}
    make new to recipient at newMessage with properties {email address:{address:"cflores@centerstreetlending.com"}}
    open newMessage
    

    set newMessage to make new outgoing message with properties {subject:"CSL Resale Advantage – Your Custom Referral Link", content:"Hey Daniel,<br><br>Check out the new website here: https://www.centerstreetlending.com/resale-advantage<br>Thanks for joining the information session this week on the new CSL Resale Advantage program! <br><br>Below is your custom link to send to your borrowers:<br><br>https://www.centerstreetlending.com/resale-advantage?rep=dayache<br><br>When a borrower uses your link, your information is automatically pushed through the form and marked in the system. As a backup, we can also always confirm you are the referral by communicating directly with Innovate Realty. <br><br>If you'd like to make a custom email signature with your URL, feel free to add it into your Signature block to get evergreen marketing for your referral link. <br><br>*Example: Find out how CSL borrowers are getting 1% exclusive listing fees on their next sale. [Learn more here.]*<br><br>If you have any questions about the program or need additional info, please reach out directly to Suzanne or Paul:<br><br>Suzanne Seini  <br>Innovate Realty  <br>suzanne@innovaterealty.com  <br><br><br>*— OR —*<br><br><br>Paul Hanson  <br>phanson@byebyehouse.com  <br><br><br>Thanks,<br><br>Greg"}
    make new to recipient at newMessage with properties {email address:{address:"dayache@centerstreetlending.com"}}
    open newMessage
    

    set newMessage to make new outgoing message with properties {subject:"CSL Resale Advantage – Your Custom Referral Link", content:"Hey Diana,<br><br>Check out the new website here: https://www.centerstreetlending.com/resale-advantage<br>Thanks for joining the information session this week on the new CSL Resale Advantage program! <br><br>Below is your custom link to send to your borrowers:<br><br>https://www.centerstreetlending.com/resale-advantage?rep=dsmith<br><br>When a borrower uses your link, your information is automatically pushed through the form and marked in the system. As a backup, we can also always confirm you are the referral by communicating directly with Innovate Realty. <br><br>If you'd like to make a custom email signature with your URL, feel free to add it into your Signature block to get evergreen marketing for your referral link. <br><br>*Example: Find out how CSL borrowers are getting 1% exclusive listing fees on their next sale. [Learn more here.]*<br><br>If you have any questions about the program or need additional info, please reach out directly to Suzanne or Paul:<br><br>Suzanne Seini  <br>Innovate Realty  <br>suzanne@innovaterealty.com  <br><br><br>*— OR —*<br><br><br>Paul Hanson  <br>phanson@byebyehouse.com  <br><br><br>Thanks,<br><br>Greg"}
    make new to recipient at newMessage with properties {email address:{address:"dsmith@centerstreetlending.com"}}
    open newMessage
    

    set newMessage to make new outgoing message with properties {subject:"CSL Resale Advantage – Your Custom Referral Link", content:"Hey Jeremy,<br><br>Check out the new website here: https://www.centerstreetlending.com/resale-advantage<br>Thanks for joining the information session this week on the new CSL Resale Advantage program! <br><br>Below is your custom link to send to your borrowers:<br><br>https://www.centerstreetlending.com/resale-advantage?rep=jmullins<br><br>When a borrower uses your link, your information is automatically pushed through the form and marked in the system. As a backup, we can also always confirm you are the referral by communicating directly with Innovate Realty. <br><br>If you'd like to make a custom email signature with your URL, feel free to add it into your Signature block to get evergreen marketing for your referral link. <br><br>*Example: Find out how CSL borrowers are getting 1% exclusive listing fees on their next sale. [Learn more here.]*<br><br>If you have any questions about the program or need additional info, please reach out directly to Suzanne or Paul:<br><br>Suzanne Seini  <br>Innovate Realty  <br>suzanne@innovaterealty.com  <br><br><br>*— OR —*<br><br><br>Paul Hanson  <br>phanson@byebyehouse.com  <br><br><br>Thanks,<br><br>Greg"}
    make new to recipient at newMessage with properties {email address:{address:"jmulllins@centerstreetlending.com"}}
    open newMessage
    

    set newMessage to make new outgoing message with properties {subject:"CSL Resale Advantage – Your Custom Referral Link", content:"Hey Kevin,<br><br>Check out the new website here: https://www.centerstreetlending.com/resale-advantage<br>Thanks for joining the information session this week on the new CSL Resale Advantage program! <br><br>Below is your custom link to send to your borrowers:<br><br>https://www.centerstreetlending.com/resale-advantage?rep=kmartinez<br><br>When a borrower uses your link, your information is automatically pushed through the form and marked in the system. As a backup, we can also always confirm you are the referral by communicating directly with Innovate Realty. <br><br>If you'd like to make a custom email signature with your URL, feel free to add it into your Signature block to get evergreen marketing for your referral link. <br><br>*Example: Find out how CSL borrowers are getting 1% exclusive listing fees on their next sale. [Learn more here.]*<br><br>If you have any questions about the program or need additional info, please reach out directly to Suzanne or Paul:<br><br>Suzanne Seini  <br>Innovate Realty  <br>suzanne@innovaterealty.com  <br><br><br>*— OR —*<br><br><br>Paul Hanson  <br>phanson@byebyehouse.com  <br><br><br>Thanks,<br><br>Greg"}
    make new to recipient at newMessage with properties {email address:{address:"kmartinez@centerstreetlending.com"}}
    open newMessage
    

    set newMessage to make new outgoing message with properties {subject:"CSL Resale Advantage – Your Custom Referral Link", content:"Hey Luis,<br><br>Check out the new website here: https://www.centerstreetlending.com/resale-advantage<br>Thanks for joining the information session this week on the new CSL Resale Advantage program! <br><br>Below is your custom link to send to your borrowers:<br><br>https://www.centerstreetlending.com/resale-advantage?rep=lmontero<br><br>When a borrower uses your link, your information is automatically pushed through the form and marked in the system. As a backup, we can also always confirm you are the referral by communicating directly with Innovate Realty. <br><br>If you'd like to make a custom email signature with your URL, feel free to add it into your Signature block to get evergreen marketing for your referral link. <br><br>*Example: Find out how CSL borrowers are getting 1% exclusive listing fees on their next sale. [Learn more here.]*<br><br>If you have any questions about the program or need additional info, please reach out directly to Suzanne or Paul:<br><br>Suzanne Seini  <br>Innovate Realty  <br>suzanne@innovaterealty.com  <br><br><br>*— OR —*<br><br><br>Paul Hanson  <br>phanson@byebyehouse.com  <br><br><br>Thanks,<br><br>Greg"}
    make new to recipient at newMessage with properties {email address:{address:"lmontero@centerstreetlending.com"}}
    open newMessage
    

    set newMessage to make new outgoing message with properties {subject:"CSL Resale Advantage – Your Custom Referral Link", content:"Hey Marlena,<br><br>Check out the new website here: https://www.centerstreetlending.com/resale-advantage<br>Thanks for joining the information session this week on the new CSL Resale Advantage program! <br><br>Below is your custom link to send to your borrowers:<br><br>https://www.centerstreetlending.com/resale-advantage?rep=mlacourse<br><br>When a borrower uses your link, your information is automatically pushed through the form and marked in the system. As a backup, we can also always confirm you are the referral by communicating directly with Innovate Realty. <br><br>If you'd like to make a custom email signature with your URL, feel free to add it into your Signature block to get evergreen marketing for your referral link. <br><br>*Example: Find out how CSL borrowers are getting 1% exclusive listing fees on their next sale. [Learn more here.]*<br><br>If you have any questions about the program or need additional info, please reach out directly to Suzanne or Paul:<br><br>Suzanne Seini  <br>Innovate Realty  <br>suzanne@innovaterealty.com  <br><br><br>*— OR —*<br><br><br>Paul Hanson  <br>phanson@byebyehouse.com  <br><br><br>Thanks,<br><br>Greg"}
    make new to recipient at newMessage with properties {email address:{address:"mlacourse@centerstreetlending.com"}}
    open newMessage
    

    set newMessage to make new outgoing message with properties {subject:"CSL Resale Advantage – Your Custom Referral Link", content:"Hey Richard,<br><br>Check out the new website here: https://www.centerstreetlending.com/resale-advantage<br>Thanks for joining the information session this week on the new CSL Resale Advantage program! <br><br>Below is your custom link to send to your borrowers:<br><br>https://www.centerstreetlending.com/resale-advantage?rep=rvu<br><br>When a borrower uses your link, your information is automatically pushed through the form and marked in the system. As a backup, we can also always confirm you are the referral by communicating directly with Innovate Realty. <br><br>If you'd like to make a custom email signature with your URL, feel free to add it into your Signature block to get evergreen marketing for your referral link. <br><br>*Example: Find out how CSL borrowers are getting 1% exclusive listing fees on their next sale. [Learn more here.]*<br><br>If you have any questions about the program or need additional info, please reach out directly to Suzanne or Paul:<br><br>Suzanne Seini  <br>Innovate Realty  <br>suzanne@innovaterealty.com  <br><br><br>*— OR —*<br><br><br>Paul Hanson  <br>phanson@byebyehouse.com  <br><br><br>Thanks,<br><br>Greg"}
    make new to recipient at newMessage with properties {email address:{address:"rvu@centerstreetlending.com"}}
    open newMessage
    

    set newMessage to make new outgoing message with properties {subject:"CSL Resale Advantage – Your Custom Referral Link", content:"Hey Ryan,<br><br>Check out the new website here: https://www.centerstreetlending.com/resale-advantage<br>Thanks for joining the information session this week on the new CSL Resale Advantage program! <br><br>Below is your custom link to send to your borrowers:<br><br>https://www.centerstreetlending.com/resale-advantage?rep=rguerrero<br><br>When a borrower uses your link, your information is automatically pushed through the form and marked in the system. As a backup, we can also always confirm you are the referral by communicating directly with Innovate Realty. <br><br>If you'd like to make a custom email signature with your URL, feel free to add it into your Signature block to get evergreen marketing for your referral link. <br><br>*Example: Find out how CSL borrowers are getting 1% exclusive listing fees on their next sale. [Learn more here.]*<br><br>If you have any questions about the program or need additional info, please reach out directly to Suzanne or Paul:<br><br>Suzanne Seini  <br>Innovate Realty  <br>suzanne@innovaterealty.com  <br><br><br>*— OR —*<br><br><br>Paul Hanson  <br>phanson@byebyehouse.com  <br><br><br>Thanks,<br><br>Greg"}
    make new to recipient at newMessage with properties {email address:{address:"rguerrero@centerstreetlending.com"}}
    open newMessage
    

    set newMessage to make new outgoing message with properties {subject:"CSL Resale Advantage – Your Custom Referral Link", content:"Hey Sherif,<br><br>Check out the new website here: https://www.centerstreetlending.com/resale-advantage<br>Thanks for joining the information session this week on the new CSL Resale Advantage program! <br><br>Below is your custom link to send to your borrowers:<br><br>https://www.centerstreetlending.com/resale-advantage?rep=shashem<br><br>When a borrower uses your link, your information is automatically pushed through the form and marked in the system. As a backup, we can also always confirm you are the referral by communicating directly with Innovate Realty. <br><br>If you'd like to make a custom email signature with your URL, feel free to add it into your Signature block to get evergreen marketing for your referral link. <br><br>*Example: Find out how CSL borrowers are getting 1% exclusive listing fees on their next sale. [Learn more here.]*<br><br>If you have any questions about the program or need additional info, please reach out directly to Suzanne or Paul:<br><br>Suzanne Seini  <br>Innovate Realty  <br>suzanne@innovaterealty.com  <br><br><br>*— OR —*<br><br><br>Paul Hanson  <br>phanson@byebyehouse.com  <br><br><br>Thanks,<br><br>Greg"}
    make new to recipient at newMessage with properties {email address:{address:"shashem@centerstreetlending.com"}}
    open newMessage
    

    set newMessage to make new outgoing message with properties {subject:"CSL Resale Advantage – Your Custom Referral Link", content:"Hey Erik,<br><br>Check out the new website here: https://www.centerstreetlending.com/resale-advantage<br>Thanks for joining the information session this week on the new CSL Resale Advantage program! <br><br>Below is your custom link to send to your borrowers:<br><br>https://www.centerstreetlending.com/resale-advantage?rep=ebrown<br><br>When a borrower uses your link, your information is automatically pushed through the form and marked in the system. As a backup, we can also always confirm you are the referral by communicating directly with Innovate Realty. <br><br>If you'd like to make a custom email signature with your URL, feel free to add it into your Signature block to get evergreen marketing for your referral link. <br><br>*Example: Find out how CSL borrowers are getting 1% exclusive listing fees on their next sale. [Learn more here.]*<br><br>If you have any questions about the program or need additional info, please reach out directly to Suzanne or Paul:<br><br>Suzanne Seini  <br>Innovate Realty  <br>suzanne@innovaterealty.com  <br><br><br>*— OR —*<br><br><br>Paul Hanson  <br>phanson@byebyehouse.com  <br><br><br>Thanks,<br><br>Greg"}
    make new to recipient at newMessage with properties {email address:{address:"ebrown@centerstreetlending.com"}}
    open newMessage
    

    set newMessage to make new outgoing message with properties {subject:"CSL Resale Advantage – Your Custom Referral Link", content:"Hey Jeremiah,<br><br>Check out the new website here: https://www.centerstreetlending.com/resale-advantage<br>Thanks for joining the information session this week on the new CSL Resale Advantage program! <br><br>Below is your custom link to send to your borrowers:<br><br>https://www.centerstreetlending.com/resale-advantage?rep=jwiedman<br><br>When a borrower uses your link, your information is automatically pushed through the form and marked in the system. As a backup, we can also always confirm you are the referral by communicating directly with Innovate Realty. <br><br>If you'd like to make a custom email signature with your URL, feel free to add it into your Signature block to get evergreen marketing for your referral link. <br><br>*Example: Find out how CSL borrowers are getting 1% exclusive listing fees on their next sale. [Learn more here.]*<br><br>If you have any questions about the program or need additional info, please reach out directly to Suzanne or Paul:<br><br>Suzanne Seini  <br>Innovate Realty  <br>suzanne@innovaterealty.com  <br><br><br>*— OR —*<br><br><br>Paul Hanson  <br>phanson@byebyehouse.com  <br><br><br>Thanks,<br><br>Greg"}
    make new to recipient at newMessage with properties {email address:{address:"jwiedman@centerstreetlending.com"}}
    open newMessage
    

    set newMessage to make new outgoing message with properties {subject:"CSL Resale Advantage – Your Custom Referral Link", content:"Hey Justin,<br><br>Check out the new website here: https://www.centerstreetlending.com/resale-advantage<br>Thanks for joining the information session this week on the new CSL Resale Advantage program! <br><br>Below is your custom link to send to your borrowers:<br><br>https://www.centerstreetlending.com/resale-advantage?rep=jwollm<br><br>When a borrower uses your link, your information is automatically pushed through the form and marked in the system. As a backup, we can also always confirm you are the referral by communicating directly with Innovate Realty. <br><br>If you'd like to make a custom email signature with your URL, feel free to add it into your Signature block to get evergreen marketing for your referral link. <br><br>*Example: Find out how CSL borrowers are getting 1% exclusive listing fees on their next sale. [Learn more here.]*<br><br>If you have any questions about the program or need additional info, please reach out directly to Suzanne or Paul:<br><br>Suzanne Seini  <br>Innovate Realty  <br>suzanne@innovaterealty.com  <br><br><br>*— OR —*<br><br><br>Paul Hanson  <br>phanson@byebyehouse.com  <br><br><br>Thanks,<br><br>Greg"}
    make new to recipient at newMessage with properties {email address:{address:"jwollm@centerstreetlending.com"}}
    open newMessage
    

    set newMessage to make new outgoing message with properties {subject:"CSL Resale Advantage – Your Custom Referral Link", content:"Hey Ryan,<br><br>Check out the new website here: https://www.centerstreetlending.com/resale-advantage<br>Thanks for joining the information session this week on the new CSL Resale Advantage program! <br><br>Below is your custom link to send to your borrowers:<br><br>https://www.centerstreetlending.com/resale-advantage?rep=rstjohn<br><br>When a borrower uses your link, your information is automatically pushed through the form and marked in the system. As a backup, we can also always confirm you are the referral by communicating directly with Innovate Realty. <br><br>If you'd like to make a custom email signature with your URL, feel free to add it into your Signature block to get evergreen marketing for your referral link. <br><br>*Example: Find out how CSL borrowers are getting 1% exclusive listing fees on their next sale. [Learn more here.]*<br><br>If you have any questions about the program or need additional info, please reach out directly to Suzanne or Paul:<br><br>Suzanne Seini  <br>Innovate Realty  <br>suzanne@innovaterealty.com  <br><br><br>*— OR —*<br><br><br>Paul Hanson  <br>phanson@byebyehouse.com  <br><br><br>Thanks,<br><br>Greg"}
    make new to recipient at newMessage with properties {email address:{address:"rstjohn@centerstreetlending.com"}}
    open newMessage
    

    set newMessage to make new outgoing message with properties {subject:"CSL Resale Advantage – Your Custom Referral Link", content:"Hey Tanner,<br><br>Check out the new website here: https://www.centerstreetlending.com/resale-advantage<br>Thanks for joining the information session this week on the new CSL Resale Advantage program! <br><br>Below is your custom link to send to your borrowers:<br><br>https://www.centerstreetlending.com/resale-advantage?rep=tpodres<br><br>When a borrower uses your link, your information is automatically pushed through the form and marked in the system. As a backup, we can also always confirm you are the referral by communicating directly with Innovate Realty. <br><br>If you'd like to make a custom email signature with your URL, feel free to add it into your Signature block to get evergreen marketing for your referral link. <br><br>*Example: Find out how CSL borrowers are getting 1% exclusive listing fees on their next sale. [Learn more here.]*<br><br>If you have any questions about the program or need additional info, please reach out directly to Suzanne or Paul:<br><br>Suzanne Seini  <br>Innovate Realty  <br>suzanne@innovaterealty.com  <br><br><br>*— OR —*<br><br><br>Paul Hanson  <br>phanson@byebyehouse.com  <br><br><br>Thanks,<br><br>Greg"}
    make new to recipient at newMessage with properties {email address:{address:"tpodres@centerstreetlending.com"}}
    open newMessage
    

    set newMessage to make new outgoing message with properties {subject:"CSL Resale Advantage – Your Custom Referral Link", content:"Hey Angie,<br><br>Check out the new website here: https://www.centerstreetlending.com/resale-advantage<br>Thanks for joining the information session this week on the new CSL Resale Advantage program! <br><br>Below is your custom link to send to your borrowers:<br><br>https://www.centerstreetlending.com/resale-advantage?rep=aallen<br><br>When a borrower uses your link, your information is automatically pushed through the form and marked in the system. As a backup, we can also always confirm you are the referral by communicating directly with Innovate Realty. <br><br>If you'd like to make a custom email signature with your URL, feel free to add it into your Signature block to get evergreen marketing for your referral link. <br><br>*Example: Find out how CSL borrowers are getting 1% exclusive listing fees on their next sale. [Learn more here.]*<br><br>If you have any questions about the program or need additional info, please reach out directly to Suzanne or Paul:<br><br>Suzanne Seini  <br>Innovate Realty  <br>suzanne@innovaterealty.com  <br><br><br>*— OR —*<br><br><br>Paul Hanson  <br>phanson@byebyehouse.com  <br><br><br>Thanks,<br><br>Greg"}
    make new to recipient at newMessage with properties {email address:{address:"aallen@centerstreetlending.com"}}
    open newMessage
    

    set newMessage to make new outgoing message with properties {subject:"CSL Resale Advantage – Your Custom Referral Link", content:"Hey Austin,<br><br>Check out the new website here: https://www.centerstreetlending.com/resale-advantage<br>Thanks for joining the information session this week on the new CSL Resale Advantage program! <br><br>Below is your custom link to send to your borrowers:<br><br>https://www.centerstreetlending.com/resale-advantage?rep=asteedman<br><br>When a borrower uses your link, your information is automatically pushed through the form and marked in the system. As a backup, we can also always confirm you are the referral by communicating directly with Innovate Realty. <br><br>If you'd like to make a custom email signature with your URL, feel free to add it into your Signature block to get evergreen marketing for your referral link. <br><br>*Example: Find out how CSL borrowers are getting 1% exclusive listing fees on their next sale. [Learn more here.]*<br><br>If you have any questions about the program or need additional info, please reach out directly to Suzanne or Paul:<br><br>Suzanne Seini  <br>Innovate Realty  <br>suzanne@innovaterealty.com  <br><br><br>*— OR —*<br><br><br>Paul Hanson  <br>phanson@byebyehouse.com  <br><br><br>Thanks,<br><br>Greg"}
    make new to recipient at newMessage with properties {email address:{address:"asteedman@centerstreetlending.com"}}
    open newMessage
    

    set newMessage to make new outgoing message with properties {subject:"CSL Resale Advantage – Your Custom Referral Link", content:"Hey Kara,<br><br>Check out the new website here: https://www.centerstreetlending.com/resale-advantage<br>Thanks for joining the information session this week on the new CSL Resale Advantage program! <br><br>Below is your custom link to send to your borrowers:<br><br>https://www.centerstreetlending.com/resale-advantage?rep=karmstrong<br><br>When a borrower uses your link, your information is automatically pushed through the form and marked in the system. As a backup, we can also always confirm you are the referral by communicating directly with Innovate Realty. <br><br>If you'd like to make a custom email signature with your URL, feel free to add it into your Signature block to get evergreen marketing for your referral link. <br><br>*Example: Find out how CSL borrowers are getting 1% exclusive listing fees on their next sale. [Learn more here.]*<br><br>If you have any questions about the program or need additional info, please reach out directly to Suzanne or Paul:<br><br>Suzanne Seini  <br>Innovate Realty  <br>suzanne@innovaterealty.com  <br><br><br>*— OR —*<br><br><br>Paul Hanson  <br>phanson@byebyehouse.com  <br><br><br>Thanks,<br><br>Greg"}
    make new to recipient at newMessage with properties {email address:{address:"karmstrong@centerstreetlending.com"}}
    open newMessage
    

    set newMessage to make new outgoing message with properties {subject:"CSL Resale Advantage – Your Custom Referral Link", content:"Hey Max,<br><br>Check out the new website here: https://www.centerstreetlending.com/resale-advantage<br>Thanks for joining the information session this week on the new CSL Resale Advantage program! <br><br>Below is your custom link to send to your borrowers:<br><br>https://www.centerstreetlending.com/resale-advantage?rep=mwoodyard<br><br>When a borrower uses your link, your information is automatically pushed through the form and marked in the system. As a backup, we can also always confirm you are the referral by communicating directly with Innovate Realty. <br><br>If you'd like to make a custom email signature with your URL, feel free to add it into your Signature block to get evergreen marketing for your referral link. <br><br>*Example: Find out how CSL borrowers are getting 1% exclusive listing fees on their next sale. [Learn more here.]*<br><br>If you have any questions about the program or need additional info, please reach out directly to Suzanne or Paul:<br><br>Suzanne Seini  <br>Innovate Realty  <br>suzanne@innovaterealty.com  <br><br><br>*— OR —*<br><br><br>Paul Hanson  <br>phanson@byebyehouse.com  <br><br><br>Thanks,<br><br>Greg"}
    make new to recipient at newMessage with properties {email address:{address:"mwoodyard@centerstreetlending.com"}}
    open newMessage
    

    set newMessage to make new outgoing message with properties {subject:"CSL Resale Advantage – Your Custom Referral Link", content:"Hey Michael,<br><br>Check out the new website here: https://www.centerstreetlending.com/resale-advantage<br>Thanks for joining the information session this week on the new CSL Resale Advantage program! <br><br>Below is your custom link to send to your borrowers:<br><br>https://www.centerstreetlending.com/resale-advantage?rep=mprice<br><br>When a borrower uses your link, your information is automatically pushed through the form and marked in the system. As a backup, we can also always confirm you are the referral by communicating directly with Innovate Realty. <br><br>If you'd like to make a custom email signature with your URL, feel free to add it into your Signature block to get evergreen marketing for your referral link. <br><br>*Example: Find out how CSL borrowers are getting 1% exclusive listing fees on their next sale. [Learn more here.]*<br><br>If you have any questions about the program or need additional info, please reach out directly to Suzanne or Paul:<br><br>Suzanne Seini  <br>Innovate Realty  <br>suzanne@innovaterealty.com  <br><br><br>*— OR —*<br><br><br>Paul Hanson  <br>phanson@byebyehouse.com  <br><br><br>Thanks,<br><br>Greg"}
    make new to recipient at newMessage with properties {email address:{address:"mprice@centerstreetlending.com"}}
    open newMessage
    

    set newMessage to make new outgoing message with properties {subject:"CSL Resale Advantage – Your Custom Referral Link", content:"Hey Robert,<br><br>Check out the new website here: https://www.centerstreetlending.com/resale-advantage<br>Thanks for joining the information session this week on the new CSL Resale Advantage program! <br><br>Below is your custom link to send to your borrowers:<br><br>https://www.centerstreetlending.com/resale-advantage?rep=rnewcomer<br><br>When a borrower uses your link, your information is automatically pushed through the form and marked in the system. As a backup, we can also always confirm you are the referral by communicating directly with Innovate Realty. <br><br>If you'd like to make a custom email signature with your URL, feel free to add it into your Signature block to get evergreen marketing for your referral link. <br><br>*Example: Find out how CSL borrowers are getting 1% exclusive listing fees on their next sale. [Learn more here.]*<br><br>If you have any questions about the program or need additional info, please reach out directly to Suzanne or Paul:<br><br>Suzanne Seini  <br>Innovate Realty  <br>suzanne@innovaterealty.com  <br><br><br>*— OR —*<br><br><br>Paul Hanson  <br>phanson@byebyehouse.com  <br><br><br>Thanks,<br><br>Greg"}
    make new to recipient at newMessage with properties {email address:{address:"rnewcomer@centerstreetlending.com"}}
    open newMessage
    

    set newMessage to make new outgoing message with properties {subject:"CSL Resale Advantage – Your Custom Referral Link", content:"Hey Sean,<br><br>Check out the new website here: https://www.centerstreetlending.com/resale-advantage<br>Thanks for joining the information session this week on the new CSL Resale Advantage program! <br><br>Below is your custom link to send to your borrowers:<br><br>https://www.centerstreetlending.com/resale-advantage?rep=sburbidge<br><br>When a borrower uses your link, your information is automatically pushed through the form and marked in the system. As a backup, we can also always confirm you are the referral by communicating directly with Innovate Realty. <br><br>If you'd like to make a custom email signature with your URL, feel free to add it into your Signature block to get evergreen marketing for your referral link. <br><br>*Example: Find out how CSL borrowers are getting 1% exclusive listing fees on their next sale. [Learn more here.]*<br><br>If you have any questions about the program or need additional info, please reach out directly to Suzanne or Paul:<br><br>Suzanne Seini  <br>Innovate Realty  <br>suzanne@innovaterealty.com  <br><br><br>*— OR —*<br><br><br>Paul Hanson  <br>phanson@byebyehouse.com  <br><br><br>Thanks,<br><br>Greg"}
    make new to recipient at newMessage with properties {email address:{address:"sburbidge@centerstreetlending.com"}}
    open newMessage
    

    set newMessage to make new outgoing message with properties {subject:"CSL Resale Advantage – Your Custom Referral Link", content:"Hey Dallin,<br><br>Check out the new website here: https://www.centerstreetlending.com/resale-advantage<br>Thanks for joining the information session this week on the new CSL Resale Advantage program! <br><br>Below is your custom link to send to your borrowers:<br><br>https://www.centerstreetlending.com/resale-advantage?rep=dwaldvogel<br><br>When a borrower uses your link, your information is automatically pushed through the form and marked in the system. As a backup, we can also always confirm you are the referral by communicating directly with Innovate Realty. <br><br>If you'd like to make a custom email signature with your URL, feel free to add it into your Signature block to get evergreen marketing for your referral link. <br><br>*Example: Find out how CSL borrowers are getting 1% exclusive listing fees on their next sale. [Learn more here.]*<br><br>If you have any questions about the program or need additional info, please reach out directly to Suzanne or Paul:<br><br>Suzanne Seini  <br>Innovate Realty  <br>suzanne@innovaterealty.com  <br><br><br>*— OR —*<br><br><br>Paul Hanson  <br>phanson@byebyehouse.com  <br><br><br>Thanks,<br><br>Greg"}
    make new to recipient at newMessage with properties {email address:{address:"dwaldvogel@centerstreetlending.com"}}
    open newMessage
    

    set newMessage to make new outgoing message with properties {subject:"CSL Resale Advantage – Your Custom Referral Link", content:"Hey Ford,<br><br>Check out the new website here: https://www.centerstreetlending.com/resale-advantage<br>Thanks for joining the information session this week on the new CSL Resale Advantage program! <br><br>Below is your custom link to send to your borrowers:<br><br>https://www.centerstreetlending.com/resale-advantage?rep=ffairon<br><br>When a borrower uses your link, your information is automatically pushed through the form and marked in the system. As a backup, we can also always confirm you are the referral by communicating directly with Innovate Realty. <br><br>If you'd like to make a custom email signature with your URL, feel free to add it into your Signature block to get evergreen marketing for your referral link. <br><br>*Example: Find out how CSL borrowers are getting 1% exclusive listing fees on their next sale. [Learn more here.]*<br><br>If you have any questions about the program or need additional info, please reach out directly to Suzanne or Paul:<br><br>Suzanne Seini  <br>Innovate Realty  <br>suzanne@innovaterealty.com  <br><br><br>*— OR —*<br><br><br>Paul Hanson  <br>phanson@byebyehouse.com  <br><br><br>Thanks,<br><br>Greg"}
    make new to recipient at newMessage with properties {email address:{address:"ffairon@centerstreetlending.com"}}
    open newMessage
    

    set newMessage to make new outgoing message with properties {subject:"CSL Resale Advantage – Your Custom Referral Link", content:"Hey Guy,<br><br>Check out the new website here: https://www.centerstreetlending.com/resale-advantage<br>Thanks for joining the information session this week on the new CSL Resale Advantage program! <br><br>Below is your custom link to send to your borrowers:<br><br>https://www.centerstreetlending.com/resale-advantage?rep=gclauss<br><br>When a borrower uses your link, your information is automatically pushed through the form and marked in the system. As a backup, we can also always confirm you are the referral by communicating directly with Innovate Realty. <br><br>If you'd like to make a custom email signature with your URL, feel free to add it into your Signature block to get evergreen marketing for your referral link. <br><br>*Example: Find out how CSL borrowers are getting 1% exclusive listing fees on their next sale. [Learn more here.]*<br><br>If you have any questions about the program or need additional info, please reach out directly to Suzanne or Paul:<br><br>Suzanne Seini  <br>Innovate Realty  <br>suzanne@innovaterealty.com  <br><br><br>*— OR —*<br><br><br>Paul Hanson  <br>phanson@byebyehouse.com  <br><br><br>Thanks,<br><br>Greg"}
    make new to recipient at newMessage with properties {email address:{address:"gclauss@centerstreetlending.com"}}
    open newMessage
    

    set newMessage to make new outgoing message with properties {subject:"CSL Resale Advantage – Your Custom Referral Link", content:"Hey Jack,<br><br>Check out the new website here: https://www.centerstreetlending.com/resale-advantage<br>Thanks for joining the information session this week on the new CSL Resale Advantage program! <br><br>Below is your custom link to send to your borrowers:<br><br>https://www.centerstreetlending.com/resale-advantage?rep=jguenther<br><br>When a borrower uses your link, your information is automatically pushed through the form and marked in the system. As a backup, we can also always confirm you are the referral by communicating directly with Innovate Realty. <br><br>If you'd like to make a custom email signature with your URL, feel free to add it into your Signature block to get evergreen marketing for your referral link. <br><br>*Example: Find out how CSL borrowers are getting 1% exclusive listing fees on their next sale. [Learn more here.]*<br><br>If you have any questions about the program or need additional info, please reach out directly to Suzanne or Paul:<br><br>Suzanne Seini  <br>Innovate Realty  <br>suzanne@innovaterealty.com  <br><br><br>*— OR —*<br><br><br>Paul Hanson  <br>phanson@byebyehouse.com  <br><br><br>Thanks,<br><br>Greg"}
    make new to recipient at newMessage with properties {email address:{address:"jguenther@centerstreetlending.com"}}
    open newMessage
    

    set newMessage to make new outgoing message with properties {subject:"CSL Resale Advantage – Your Custom Referral Link", content:"Hey Ryan,<br><br>Check out the new website here: https://www.centerstreetlending.com/resale-advantage<br>Thanks for joining the information session this week on the new CSL Resale Advantage program! <br><br>Below is your custom link to send to your borrowers:<br><br>https://www.centerstreetlending.com/resale-advantage?rep=rclayton<br><br>When a borrower uses your link, your information is automatically pushed through the form and marked in the system. As a backup, we can also always confirm you are the referral by communicating directly with Innovate Realty. <br><br>If you'd like to make a custom email signature with your URL, feel free to add it into your Signature block to get evergreen marketing for your referral link. <br><br>*Example: Find out how CSL borrowers are getting 1% exclusive listing fees on their next sale. [Learn more here.]*<br><br>If you have any questions about the program or need additional info, please reach out directly to Suzanne or Paul:<br><br>Suzanne Seini  <br>Innovate Realty  <br>suzanne@innovaterealty.com  <br><br><br>*— OR —*<br><br><br>Paul Hanson  <br>phanson@byebyehouse.com  <br><br><br>Thanks,<br><br>Greg"}
    make new to recipient at newMessage with properties {email address:{address:"rclayton@centerstreetlending.com"}}
    open newMessage
    

    set newMessage to make new outgoing message with properties {subject:"CSL Resale Advantage – Your Custom Referral Link", content:"Hey Sean,<br><br>Check out the new website here: https://www.centerstreetlending.com/resale-advantage<br>Thanks for joining the information session this week on the new CSL Resale Advantage program! <br><br>Below is your custom link to send to your borrowers:<br><br>https://www.centerstreetlending.com/resale-advantage?rep=sklement<br><br>When a borrower uses your link, your information is automatically pushed through the form and marked in the system. As a backup, we can also always confirm you are the referral by communicating directly with Innovate Realty. <br><br>If you'd like to make a custom email signature with your URL, feel free to add it into your Signature block to get evergreen marketing for your referral link. <br><br>*Example: Find out how CSL borrowers are getting 1% exclusive listing fees on their next sale. [Learn more here.]*<br><br>If you have any questions about the program or need additional info, please reach out directly to Suzanne or Paul:<br><br>Suzanne Seini  <br>Innovate Realty  <br>suzanne@innovaterealty.com  <br><br><br>*— OR —*<br><br><br>Paul Hanson  <br>phanson@byebyehouse.com  <br><br><br>Thanks,<br><br>Greg"}
    make new to recipient at newMessage with properties {email address:{address:"sklement@centerstreetlending.com"}}
    open newMessage
    

    set newMessage to make new outgoing message with properties {subject:"CSL Resale Advantage – Your Custom Referral Link", content:"Hey Brandon,<br><br>Check out the new website here: https://www.centerstreetlending.com/resale-advantage<br>Thanks for joining the information session this week on the new CSL Resale Advantage program! <br><br>Below is your custom link to send to your borrowers:<br><br>https://www.centerstreetlending.com/resale-advantage?rep=bherbert<br><br>When a borrower uses your link, your information is automatically pushed through the form and marked in the system. As a backup, we can also always confirm you are the referral by communicating directly with Innovate Realty. <br><br>If you'd like to make a custom email signature with your URL, feel free to add it into your Signature block to get evergreen marketing for your referral link. <br><br>*Example: Find out how CSL borrowers are getting 1% exclusive listing fees on their next sale. [Learn more here.]*<br><br>If you have any questions about the program or need additional info, please reach out directly to Suzanne or Paul:<br><br>Suzanne Seini  <br>Innovate Realty  <br>suzanne@innovaterealty.com  <br><br><br>*— OR —*<br><br><br>Paul Hanson  <br>phanson@byebyehouse.com  <br><br><br>Thanks,<br><br>Greg"}
    make new to recipient at newMessage with properties {email address:{address:"bherbert@centerstreetlending.com"}}
    open newMessage
    

    set newMessage to make new outgoing message with properties {subject:"CSL Resale Advantage – Your Custom Referral Link", content:"Hey Crystal,<br><br>Check out the new website here: https://www.centerstreetlending.com/resale-advantage<br>Thanks for joining the information session this week on the new CSL Resale Advantage program! <br><br>Below is your custom link to send to your borrowers:<br><br>https://www.centerstreetlending.com/resale-advantage?rep=cmora<br><br>When a borrower uses your link, your information is automatically pushed through the form and marked in the system. As a backup, we can also always confirm you are the referral by communicating directly with Innovate Realty. <br><br>If you'd like to make a custom email signature with your URL, feel free to add it into your Signature block to get evergreen marketing for your referral link. <br><br>*Example: Find out how CSL borrowers are getting 1% exclusive listing fees on their next sale. [Learn more here.]*<br><br>If you have any questions about the program or need additional info, please reach out directly to Suzanne or Paul:<br><br>Suzanne Seini  <br>Innovate Realty  <br>suzanne@innovaterealty.com  <br><br><br>*— OR —*<br><br><br>Paul Hanson  <br>phanson@byebyehouse.com  <br><br><br>Thanks,<br><br>Greg"}
    make new to recipient at newMessage with properties {email address:{address:"cmora@centerstreetlending.com"}}
    open newMessage
    

    set newMessage to make new outgoing message with properties {subject:"CSL Resale Advantage – Your Custom Referral Link", content:"Hey Jacob,<br><br>Check out the new website here: https://www.centerstreetlending.com/resale-advantage<br>Thanks for joining the information session this week on the new CSL Resale Advantage program! <br><br>Below is your custom link to send to your borrowers:<br><br>https://www.centerstreetlending.com/resale-advantage?rep=jwoodyard<br><br>When a borrower uses your link, your information is automatically pushed through the form and marked in the system. As a backup, we can also always confirm you are the referral by communicating directly with Innovate Realty. <br><br>If you'd like to make a custom email signature with your URL, feel free to add it into your Signature block to get evergreen marketing for your referral link. <br><br>*Example: Find out how CSL borrowers are getting 1% exclusive listing fees on their next sale. [Learn more here.]*<br><br>If you have any questions about the program or need additional info, please reach out directly to Suzanne or Paul:<br><br>Suzanne Seini  <br>Innovate Realty  <br>suzanne@innovaterealty.com  <br><br><br>*— OR —*<br><br><br>Paul Hanson  <br>phanson@byebyehouse.com  <br><br><br>Thanks,<br><br>Greg"}
    make new to recipient at newMessage with properties {email address:{address:"jwoodyard@centerstreetlending.com"}}
    open newMessage
    

    set newMessage to make new outgoing message with properties {subject:"CSL Resale Advantage – Your Custom Referral Link", content:"Hey Lauren,<br><br>Check out the new website here: https://www.centerstreetlending.com/resale-advantage<br>Thanks for joining the information session this week on the new CSL Resale Advantage program! <br><br>Below is your custom link to send to your borrowers:<br><br>https://www.centerstreetlending.com/resale-advantage?rep=llipinski<br><br>When a borrower uses your link, your information is automatically pushed through the form and marked in the system. As a backup, we can also always confirm you are the referral by communicating directly with Innovate Realty. <br><br>If you'd like to make a custom email signature with your URL, feel free to add it into your Signature block to get evergreen marketing for your referral link. <br><br>*Example: Find out how CSL borrowers are getting 1% exclusive listing fees on their next sale. [Learn more here.]*<br><br>If you have any questions about the program or need additional info, please reach out directly to Suzanne or Paul:<br><br>Suzanne Seini  <br>Innovate Realty  <br>suzanne@innovaterealty.com  <br><br><br>*— OR —*<br><br><br>Paul Hanson  <br>phanson@byebyehouse.com  <br><br><br>Thanks,<br><br>Greg"}
    make new to recipient at newMessage with properties {email address:{address:"llipinski@centerstreetlending.com"}}
    open newMessage
    

    set newMessage to make new outgoing message with properties {subject:"CSL Resale Advantage – Your Custom Referral Link", content:"Hey Richard,<br><br>Check out the new website here: https://www.centerstreetlending.com/resale-advantage<br>Thanks for joining the information session this week on the new CSL Resale Advantage program! <br><br>Below is your custom link to send to your borrowers:<br><br>https://www.centerstreetlending.com/resale-advantage?rep=rkim<br><br>When a borrower uses your link, your information is automatically pushed through the form and marked in the system. As a backup, we can also always confirm you are the referral by communicating directly with Innovate Realty. <br><br>If you'd like to make a custom email signature with your URL, feel free to add it into your Signature block to get evergreen marketing for your referral link. <br><br>*Example: Find out how CSL borrowers are getting 1% exclusive listing fees on their next sale. [Learn more here.]*<br><br>If you have any questions about the program or need additional info, please reach out directly to Suzanne or Paul:<br><br>Suzanne Seini  <br>Innovate Realty  <br>suzanne@innovaterealty.com  <br><br><br>*— OR —*<br><br><br>Paul Hanson  <br>phanson@byebyehouse.com  <br><br><br>Thanks,<br><br>Greg"}
    make new to recipient at newMessage with properties {email address:{address:"rkim@centerstreetlending.com"}}
    open newMessage
    

    set newMessage to make new outgoing message with properties {subject:"CSL Resale Advantage – Your Custom Referral Link", content:"Hey Trevor,<br><br>Check out the new website here: https://www.centerstreetlending.com/resale-advantage<br>Thanks for joining the information session this week on the new CSL Resale Advantage program! <br><br>Below is your custom link to send to your borrowers:<br><br>https://www.centerstreetlending.com/resale-advantage?rep=tburbidge<br><br>When a borrower uses your link, your information is automatically pushed through the form and marked in the system. As a backup, we can also always confirm you are the referral by communicating directly with Innovate Realty. <br><br>If you'd like to make a custom email signature with your URL, feel free to add it into your Signature block to get evergreen marketing for your referral link. <br><br>*Example: Find out how CSL borrowers are getting 1% exclusive listing fees on their next sale. [Learn more here.]*<br><br>If you have any questions about the program or need additional info, please reach out directly to Suzanne or Paul:<br><br>Suzanne Seini  <br>Innovate Realty  <br>suzanne@innovaterealty.com  <br><br><br>*— OR —*<br><br><br>Paul Hanson  <br>phanson@byebyehouse.com  <br><br><br>Thanks,<br><br>Greg"}
    make new to recipient at newMessage with properties {email address:{address:"tburbidge@centerstreetlending.com"}}
    open newMessage
    

    set newMessage to make new outgoing message with properties {subject:"CSL Resale Advantage – Your Custom Referral Link", content:"Hey Jacob,<br><br>Check out the new website here: https://www.centerstreetlending.com/resale-advantage<br>Thanks for joining the information session this week on the new CSL Resale Advantage program! <br><br>Below is your custom link to send to your borrowers:<br><br>https://www.centerstreetlending.com/resale-advantage?rep=jcho<br><br>When a borrower uses your link, your information is automatically pushed through the form and marked in the system. As a backup, we can also always confirm you are the referral by communicating directly with Innovate Realty. <br><br>If you'd like to make a custom email signature with your URL, feel free to add it into your Signature block to get evergreen marketing for your referral link. <br><br>*Example: Find out how CSL borrowers are getting 1% exclusive listing fees on their next sale. [Learn more here.]*<br><br>If you have any questions about the program or need additional info, please reach out directly to Suzanne or Paul:<br><br>Suzanne Seini  <br>Innovate Realty  <br>suzanne@innovaterealty.com  <br><br><br>*— OR —*<br><br><br>Paul Hanson  <br>phanson@byebyehouse.com  <br><br><br>Thanks,<br><br>Greg"}
    make new to recipient at newMessage with properties {email address:{address:"jcho@centerstreetlending.com"}}
    open newMessage
    
end tell