tell application "Microsoft Outlook"

    set newMessage to make new outgoing message with properties {subject:"CSL Resale Advantage – Your Custom Referral Link", content:"Hey Alec,\r\rCheck out the new website here: https://www.centerstreetlending.com/resale-advantage\rThanks for joining the information session this week on the new CSL Resale Advantage program! \r\rBelow is your custom link to send to your borrowers:\r\rhttps://www.centerstreetlending.com/resale-advantage?rep=aralph\r\rWhen a borrower uses your link, your information is automatically pushed through the form and marked in the system. As a backup, we can also always confirm you are the referral by communicating directly with Innovate Realty. \r\rIf you'd like to make a custom email signature with your URL, feel free to add it into your Signature block to get evergreen marketing for your referral link. \r\r*Example: Find out how CSL borrowers are getting 1% exclusive listing fees on their next sale. [Learn more here.]*\r\rIf you have any questions about the program or need additional info, please reach out directly to Suzanne or Paul:\r\rSuzanne Seini  \rInnovate Realty  \rsuzanne@innovaterealty.com  \r\r\r*— OR —*\r\r\rPaul Hanson  \rphanson@byebyehouse.com  \r\r\rThanks,\r\rGreg"}
    make new to recipient at newMessage with properties {email address:{address:"aralph@centerstreetlending.com"}}
    open newMessage
    

    set newMessage to make new outgoing message with properties {subject:"CSL Resale Advantage – Your Custom Referral Link", content:"Hey Allyssa,\r\rCheck out the new website here: https://www.centerstreetlending.com/resale-advantage\rThanks for joining the information session this week on the new CSL Resale Advantage program! \r\rBelow is your custom link to send to your borrowers:\r\rhttps://www.centerstreetlending.com/resale-advantage?rep=amichaelson\r\rWhen a borrower uses your link, your information is automatically pushed through the form and marked in the system. As a backup, we can also always confirm you are the referral by communicating directly with Innovate Realty. \r\rIf you'd like to make a custom email signature with your URL, feel free to add it into your Signature block to get evergreen marketing for your referral link. \r\r*Example: Find out how CSL borrowers are getting 1% exclusive listing fees on their next sale. [Learn more here.]*\r\rIf you have any questions about the program or need additional info, please reach out directly to Suzanne or Paul:\r\rSuzanne Seini  \rInnovate Realty  \rsuzanne@innovaterealty.com  \r\r\r*— OR —*\r\r\rPaul Hanson  \rphanson@byebyehouse.com  \r\r\rThanks,\r\rGreg"}
    make new to recipient at newMessage with properties {email address:{address:"amichaelson@centerstreetlending.com"}}
    open newMessage
    

    set newMessage to make new outgoing message with properties {subject:"CSL Resale Advantage – Your Custom Referral Link", content:"Hey Angelica,\r\rCheck out the new website here: https://www.centerstreetlending.com/resale-advantage\rThanks for joining the information session this week on the new CSL Resale Advantage program! \r\rBelow is your custom link to send to your borrowers:\r\rhttps://www.centerstreetlending.com/resale-advantage?rep=anaranjo\r\rWhen a borrower uses your link, your information is automatically pushed through the form and marked in the system. As a backup, we can also always confirm you are the referral by communicating directly with Innovate Realty. \r\rIf you'd like to make a custom email signature with your URL, feel free to add it into your Signature block to get evergreen marketing for your referral link. \r\r*Example: Find out how CSL borrowers are getting 1% exclusive listing fees on their next sale. [Learn more here.]*\r\rIf you have any questions about the program or need additional info, please reach out directly to Suzanne or Paul:\r\rSuzanne Seini  \rInnovate Realty  \rsuzanne@innovaterealty.com  \r\r\r*— OR —*\r\r\rPaul Hanson  \rphanson@byebyehouse.com  \r\r\rThanks,\r\rGreg"}
    make new to recipient at newMessage with properties {email address:{address:"anaranjo@centerstreetlending.com"}}
    open newMessage
    

    set newMessage to make new outgoing message with properties {subject:"CSL Resale Advantage – Your Custom Referral Link", content:"Hey Christine,\r\rCheck out the new website here: https://www.centerstreetlending.com/resale-advantage\rThanks for joining the information session this week on the new CSL Resale Advantage program! \r\rBelow is your custom link to send to your borrowers:\r\rhttps://www.centerstreetlending.com/resale-advantage?rep=cflores\r\rWhen a borrower uses your link, your information is automatically pushed through the form and marked in the system. As a backup, we can also always confirm you are the referral by communicating directly with Innovate Realty. \r\rIf you'd like to make a custom email signature with your URL, feel free to add it into your Signature block to get evergreen marketing for your referral link. \r\r*Example: Find out how CSL borrowers are getting 1% exclusive listing fees on their next sale. [Learn more here.]*\r\rIf you have any questions about the program or need additional info, please reach out directly to Suzanne or Paul:\r\rSuzanne Seini  \rInnovate Realty  \rsuzanne@innovaterealty.com  \r\r\r*— OR —*\r\r\rPaul Hanson  \rphanson@byebyehouse.com  \r\r\rThanks,\r\rGreg"}
    make new to recipient at newMessage with properties {email address:{address:"cflores@centerstreetlending.com"}}
    open newMessage
    

    set newMessage to make new outgoing message with properties {subject:"CSL Resale Advantage – Your Custom Referral Link", content:"Hey Daniel,\r\rCheck out the new website here: https://www.centerstreetlending.com/resale-advantage\rThanks for joining the information session this week on the new CSL Resale Advantage program! \r\rBelow is your custom link to send to your borrowers:\r\rhttps://www.centerstreetlending.com/resale-advantage?rep=dayache\r\rWhen a borrower uses your link, your information is automatically pushed through the form and marked in the system. As a backup, we can also always confirm you are the referral by communicating directly with Innovate Realty. \r\rIf you'd like to make a custom email signature with your URL, feel free to add it into your Signature block to get evergreen marketing for your referral link. \r\r*Example: Find out how CSL borrowers are getting 1% exclusive listing fees on their next sale. [Learn more here.]*\r\rIf you have any questions about the program or need additional info, please reach out directly to Suzanne or Paul:\r\rSuzanne Seini  \rInnovate Realty  \rsuzanne@innovaterealty.com  \r\r\r*— OR —*\r\r\rPaul Hanson  \rphanson@byebyehouse.com  \r\r\rThanks,\r\rGreg"}
    make new to recipient at newMessage with properties {email address:{address:"dayache@centerstreetlending.com"}}
    open newMessage
    

    set newMessage to make new outgoing message with properties {subject:"CSL Resale Advantage – Your Custom Referral Link", content:"Hey Diana,\r\rCheck out the new website here: https://www.centerstreetlending.com/resale-advantage\rThanks for joining the information session this week on the new CSL Resale Advantage program! \r\rBelow is your custom link to send to your borrowers:\r\rhttps://www.centerstreetlending.com/resale-advantage?rep=dsmith\r\rWhen a borrower uses your link, your information is automatically pushed through the form and marked in the system. As a backup, we can also always confirm you are the referral by communicating directly with Innovate Realty. \r\rIf you'd like to make a custom email signature with your URL, feel free to add it into your Signature block to get evergreen marketing for your referral link. \r\r*Example: Find out how CSL borrowers are getting 1% exclusive listing fees on their next sale. [Learn more here.]*\r\rIf you have any questions about the program or need additional info, please reach out directly to Suzanne or Paul:\r\rSuzanne Seini  \rInnovate Realty  \rsuzanne@innovaterealty.com  \r\r\r*— OR —*\r\r\rPaul Hanson  \rphanson@byebyehouse.com  \r\r\rThanks,\r\rGreg"}
    make new to recipient at newMessage with properties {email address:{address:"dsmith@centerstreetlending.com"}}
    open newMessage
    

    set newMessage to make new outgoing message with properties {subject:"CSL Resale Advantage – Your Custom Referral Link", content:"Hey Jeremy,\r\rCheck out the new website here: https://www.centerstreetlending.com/resale-advantage\rThanks for joining the information session this week on the new CSL Resale Advantage program! \r\rBelow is your custom link to send to your borrowers:\r\rhttps://www.centerstreetlending.com/resale-advantage?rep=jmullins\r\rWhen a borrower uses your link, your information is automatically pushed through the form and marked in the system. As a backup, we can also always confirm you are the referral by communicating directly with Innovate Realty. \r\rIf you'd like to make a custom email signature with your URL, feel free to add it into your Signature block to get evergreen marketing for your referral link. \r\r*Example: Find out how CSL borrowers are getting 1% exclusive listing fees on their next sale. [Learn more here.]*\r\rIf you have any questions about the program or need additional info, please reach out directly to Suzanne or Paul:\r\rSuzanne Seini  \rInnovate Realty  \rsuzanne@innovaterealty.com  \r\r\r*— OR —*\r\r\rPaul Hanson  \rphanson@byebyehouse.com  \r\r\rThanks,\r\rGreg"}
    make new to recipient at newMessage with properties {email address:{address:"jmulllins@centerstreetlending.com"}}
    open newMessage
    

    set newMessage to make new outgoing message with properties {subject:"CSL Resale Advantage – Your Custom Referral Link", content:"Hey Kevin,\r\rCheck out the new website here: https://www.centerstreetlending.com/resale-advantage\rThanks for joining the information session this week on the new CSL Resale Advantage program! \r\rBelow is your custom link to send to your borrowers:\r\rhttps://www.centerstreetlending.com/resale-advantage?rep=kmartinez\r\rWhen a borrower uses your link, your information is automatically pushed through the form and marked in the system. As a backup, we can also always confirm you are the referral by communicating directly with Innovate Realty. \r\rIf you'd like to make a custom email signature with your URL, feel free to add it into your Signature block to get evergreen marketing for your referral link. \r\r*Example: Find out how CSL borrowers are getting 1% exclusive listing fees on their next sale. [Learn more here.]*\r\rIf you have any questions about the program or need additional info, please reach out directly to Suzanne or Paul:\r\rSuzanne Seini  \rInnovate Realty  \rsuzanne@innovaterealty.com  \r\r\r*— OR —*\r\r\rPaul Hanson  \rphanson@byebyehouse.com  \r\r\rThanks,\r\rGreg"}
    make new to recipient at newMessage with properties {email address:{address:"kmartinez@centerstreetlending.com"}}
    open newMessage
    

    set newMessage to make new outgoing message with properties {subject:"CSL Resale Advantage – Your Custom Referral Link", content:"Hey Luis,\r\rCheck out the new website here: https://www.centerstreetlending.com/resale-advantage\rThanks for joining the information session this week on the new CSL Resale Advantage program! \r\rBelow is your custom link to send to your borrowers:\r\rhttps://www.centerstreetlending.com/resale-advantage?rep=lmontero\r\rWhen a borrower uses your link, your information is automatically pushed through the form and marked in the system. As a backup, we can also always confirm you are the referral by communicating directly with Innovate Realty. \r\rIf you'd like to make a custom email signature with your URL, feel free to add it into your Signature block to get evergreen marketing for your referral link. \r\r*Example: Find out how CSL borrowers are getting 1% exclusive listing fees on their next sale. [Learn more here.]*\r\rIf you have any questions about the program or need additional info, please reach out directly to Suzanne or Paul:\r\rSuzanne Seini  \rInnovate Realty  \rsuzanne@innovaterealty.com  \r\r\r*— OR —*\r\r\rPaul Hanson  \rphanson@byebyehouse.com  \r\r\rThanks,\r\rGreg"}
    make new to recipient at newMessage with properties {email address:{address:"lmontero@centerstreetlending.com"}}
    open newMessage
    

    set newMessage to make new outgoing message with properties {subject:"CSL Resale Advantage – Your Custom Referral Link", content:"Hey Marlena,\r\rCheck out the new website here: https://www.centerstreetlending.com/resale-advantage\rThanks for joining the information session this week on the new CSL Resale Advantage program! \r\rBelow is your custom link to send to your borrowers:\r\rhttps://www.centerstreetlending.com/resale-advantage?rep=mlacourse\r\rWhen a borrower uses your link, your information is automatically pushed through the form and marked in the system. As a backup, we can also always confirm you are the referral by communicating directly with Innovate Realty. \r\rIf you'd like to make a custom email signature with your URL, feel free to add it into your Signature block to get evergreen marketing for your referral link. \r\r*Example: Find out how CSL borrowers are getting 1% exclusive listing fees on their next sale. [Learn more here.]*\r\rIf you have any questions about the program or need additional info, please reach out directly to Suzanne or Paul:\r\rSuzanne Seini  \rInnovate Realty  \rsuzanne@innovaterealty.com  \r\r\r*— OR —*\r\r\rPaul Hanson  \rphanson@byebyehouse.com  \r\r\rThanks,\r\rGreg"}
    make new to recipient at newMessage with properties {email address:{address:"mlacourse@centerstreetlending.com"}}
    open newMessage
    

    set newMessage to make new outgoing message with properties {subject:"CSL Resale Advantage – Your Custom Referral Link", content:"Hey Richard,\r\rCheck out the new website here: https://www.centerstreetlending.com/resale-advantage\rThanks for joining the information session this week on the new CSL Resale Advantage program! \r\rBelow is your custom link to send to your borrowers:\r\rhttps://www.centerstreetlending.com/resale-advantage?rep=rvu\r\rWhen a borrower uses your link, your information is automatically pushed through the form and marked in the system. As a backup, we can also always confirm you are the referral by communicating directly with Innovate Realty. \r\rIf you'd like to make a custom email signature with your URL, feel free to add it into your Signature block to get evergreen marketing for your referral link. \r\r*Example: Find out how CSL borrowers are getting 1% exclusive listing fees on their next sale. [Learn more here.]*\r\rIf you have any questions about the program or need additional info, please reach out directly to Suzanne or Paul:\r\rSuzanne Seini  \rInnovate Realty  \rsuzanne@innovaterealty.com  \r\r\r*— OR —*\r\r\rPaul Hanson  \rphanson@byebyehouse.com  \r\r\rThanks,\r\rGreg"}
    make new to recipient at newMessage with properties {email address:{address:"rvu@centerstreetlending.com"}}
    open newMessage
    

    set newMessage to make new outgoing message with properties {subject:"CSL Resale Advantage – Your Custom Referral Link", content:"Hey Ryan,\r\rCheck out the new website here: https://www.centerstreetlending.com/resale-advantage\rThanks for joining the information session this week on the new CSL Resale Advantage program! \r\rBelow is your custom link to send to your borrowers:\r\rhttps://www.centerstreetlending.com/resale-advantage?rep=rguerrero\r\rWhen a borrower uses your link, your information is automatically pushed through the form and marked in the system. As a backup, we can also always confirm you are the referral by communicating directly with Innovate Realty. \r\rIf you'd like to make a custom email signature with your URL, feel free to add it into your Signature block to get evergreen marketing for your referral link. \r\r*Example: Find out how CSL borrowers are getting 1% exclusive listing fees on their next sale. [Learn more here.]*\r\rIf you have any questions about the program or need additional info, please reach out directly to Suzanne or Paul:\r\rSuzanne Seini  \rInnovate Realty  \rsuzanne@innovaterealty.com  \r\r\r*— OR —*\r\r\rPaul Hanson  \rphanson@byebyehouse.com  \r\r\rThanks,\r\rGreg"}
    make new to recipient at newMessage with properties {email address:{address:"rguerrero@centerstreetlending.com"}}
    open newMessage
    

    set newMessage to make new outgoing message with properties {subject:"CSL Resale Advantage – Your Custom Referral Link", content:"Hey Sherif,\r\rCheck out the new website here: https://www.centerstreetlending.com/resale-advantage\rThanks for joining the information session this week on the new CSL Resale Advantage program! \r\rBelow is your custom link to send to your borrowers:\r\rhttps://www.centerstreetlending.com/resale-advantage?rep=shashem\r\rWhen a borrower uses your link, your information is automatically pushed through the form and marked in the system. As a backup, we can also always confirm you are the referral by communicating directly with Innovate Realty. \r\rIf you'd like to make a custom email signature with your URL, feel free to add it into your Signature block to get evergreen marketing for your referral link. \r\r*Example: Find out how CSL borrowers are getting 1% exclusive listing fees on their next sale. [Learn more here.]*\r\rIf you have any questions about the program or need additional info, please reach out directly to Suzanne or Paul:\r\rSuzanne Seini  \rInnovate Realty  \rsuzanne@innovaterealty.com  \r\r\r*— OR —*\r\r\rPaul Hanson  \rphanson@byebyehouse.com  \r\r\rThanks,\r\rGreg"}
    make new to recipient at newMessage with properties {email address:{address:"shashem@centerstreetlending.com"}}
    open newMessage
    

    set newMessage to make new outgoing message with properties {subject:"CSL Resale Advantage – Your Custom Referral Link", content:"Hey Erik,\r\rCheck out the new website here: https://www.centerstreetlending.com/resale-advantage\rThanks for joining the information session this week on the new CSL Resale Advantage program! \r\rBelow is your custom link to send to your borrowers:\r\rhttps://www.centerstreetlending.com/resale-advantage?rep=ebrown\r\rWhen a borrower uses your link, your information is automatically pushed through the form and marked in the system. As a backup, we can also always confirm you are the referral by communicating directly with Innovate Realty. \r\rIf you'd like to make a custom email signature with your URL, feel free to add it into your Signature block to get evergreen marketing for your referral link. \r\r*Example: Find out how CSL borrowers are getting 1% exclusive listing fees on their next sale. [Learn more here.]*\r\rIf you have any questions about the program or need additional info, please reach out directly to Suzanne or Paul:\r\rSuzanne Seini  \rInnovate Realty  \rsuzanne@innovaterealty.com  \r\r\r*— OR —*\r\r\rPaul Hanson  \rphanson@byebyehouse.com  \r\r\rThanks,\r\rGreg"}
    make new to recipient at newMessage with properties {email address:{address:"ebrown@centerstreetlending.com"}}
    open newMessage
    

    set newMessage to make new outgoing message with properties {subject:"CSL Resale Advantage – Your Custom Referral Link", content:"Hey Jeremiah,\r\rCheck out the new website here: https://www.centerstreetlending.com/resale-advantage\rThanks for joining the information session this week on the new CSL Resale Advantage program! \r\rBelow is your custom link to send to your borrowers:\r\rhttps://www.centerstreetlending.com/resale-advantage?rep=jwiedman\r\rWhen a borrower uses your link, your information is automatically pushed through the form and marked in the system. As a backup, we can also always confirm you are the referral by communicating directly with Innovate Realty. \r\rIf you'd like to make a custom email signature with your URL, feel free to add it into your Signature block to get evergreen marketing for your referral link. \r\r*Example: Find out how CSL borrowers are getting 1% exclusive listing fees on their next sale. [Learn more here.]*\r\rIf you have any questions about the program or need additional info, please reach out directly to Suzanne or Paul:\r\rSuzanne Seini  \rInnovate Realty  \rsuzanne@innovaterealty.com  \r\r\r*— OR —*\r\r\rPaul Hanson  \rphanson@byebyehouse.com  \r\r\rThanks,\r\rGreg"}
    make new to recipient at newMessage with properties {email address:{address:"jwiedman@centerstreetlending.com"}}
    open newMessage
    

    set newMessage to make new outgoing message with properties {subject:"CSL Resale Advantage – Your Custom Referral Link", content:"Hey Justin,\r\rCheck out the new website here: https://www.centerstreetlending.com/resale-advantage\rThanks for joining the information session this week on the new CSL Resale Advantage program! \r\rBelow is your custom link to send to your borrowers:\r\rhttps://www.centerstreetlending.com/resale-advantage?rep=jwollm\r\rWhen a borrower uses your link, your information is automatically pushed through the form and marked in the system. As a backup, we can also always confirm you are the referral by communicating directly with Innovate Realty. \r\rIf you'd like to make a custom email signature with your URL, feel free to add it into your Signature block to get evergreen marketing for your referral link. \r\r*Example: Find out how CSL borrowers are getting 1% exclusive listing fees on their next sale. [Learn more here.]*\r\rIf you have any questions about the program or need additional info, please reach out directly to Suzanne or Paul:\r\rSuzanne Seini  \rInnovate Realty  \rsuzanne@innovaterealty.com  \r\r\r*— OR —*\r\r\rPaul Hanson  \rphanson@byebyehouse.com  \r\r\rThanks,\r\rGreg"}
    make new to recipient at newMessage with properties {email address:{address:"jwollm@centerstreetlending.com"}}
    open newMessage
    

    set newMessage to make new outgoing message with properties {subject:"CSL Resale Advantage – Your Custom Referral Link", content:"Hey Ryan,\r\rCheck out the new website here: https://www.centerstreetlending.com/resale-advantage\rThanks for joining the information session this week on the new CSL Resale Advantage program! \r\rBelow is your custom link to send to your borrowers:\r\rhttps://www.centerstreetlending.com/resale-advantage?rep=rstjohn\r\rWhen a borrower uses your link, your information is automatically pushed through the form and marked in the system. As a backup, we can also always confirm you are the referral by communicating directly with Innovate Realty. \r\rIf you'd like to make a custom email signature with your URL, feel free to add it into your Signature block to get evergreen marketing for your referral link. \r\r*Example: Find out how CSL borrowers are getting 1% exclusive listing fees on their next sale. [Learn more here.]*\r\rIf you have any questions about the program or need additional info, please reach out directly to Suzanne or Paul:\r\rSuzanne Seini  \rInnovate Realty  \rsuzanne@innovaterealty.com  \r\r\r*— OR —*\r\r\rPaul Hanson  \rphanson@byebyehouse.com  \r\r\rThanks,\r\rGreg"}
    make new to recipient at newMessage with properties {email address:{address:"rstjohn@centerstreetlending.com"}}
    open newMessage
    

    set newMessage to make new outgoing message with properties {subject:"CSL Resale Advantage – Your Custom Referral Link", content:"Hey Tanner,\r\rCheck out the new website here: https://www.centerstreetlending.com/resale-advantage\rThanks for joining the information session this week on the new CSL Resale Advantage program! \r\rBelow is your custom link to send to your borrowers:\r\rhttps://www.centerstreetlending.com/resale-advantage?rep=tpodres\r\rWhen a borrower uses your link, your information is automatically pushed through the form and marked in the system. As a backup, we can also always confirm you are the referral by communicating directly with Innovate Realty. \r\rIf you'd like to make a custom email signature with your URL, feel free to add it into your Signature block to get evergreen marketing for your referral link. \r\r*Example: Find out how CSL borrowers are getting 1% exclusive listing fees on their next sale. [Learn more here.]*\r\rIf you have any questions about the program or need additional info, please reach out directly to Suzanne or Paul:\r\rSuzanne Seini  \rInnovate Realty  \rsuzanne@innovaterealty.com  \r\r\r*— OR —*\r\r\rPaul Hanson  \rphanson@byebyehouse.com  \r\r\rThanks,\r\rGreg"}
    make new to recipient at newMessage with properties {email address:{address:"tpodres@centerstreetlending.com"}}
    open newMessage
    

    set newMessage to make new outgoing message with properties {subject:"CSL Resale Advantage – Your Custom Referral Link", content:"Hey Angie,\r\rCheck out the new website here: https://www.centerstreetlending.com/resale-advantage\rThanks for joining the information session this week on the new CSL Resale Advantage program! \r\rBelow is your custom link to send to your borrowers:\r\rhttps://www.centerstreetlending.com/resale-advantage?rep=aallen\r\rWhen a borrower uses your link, your information is automatically pushed through the form and marked in the system. As a backup, we can also always confirm you are the referral by communicating directly with Innovate Realty. \r\rIf you'd like to make a custom email signature with your URL, feel free to add it into your Signature block to get evergreen marketing for your referral link. \r\r*Example: Find out how CSL borrowers are getting 1% exclusive listing fees on their next sale. [Learn more here.]*\r\rIf you have any questions about the program or need additional info, please reach out directly to Suzanne or Paul:\r\rSuzanne Seini  \rInnovate Realty  \rsuzanne@innovaterealty.com  \r\r\r*— OR —*\r\r\rPaul Hanson  \rphanson@byebyehouse.com  \r\r\rThanks,\r\rGreg"}
    make new to recipient at newMessage with properties {email address:{address:"aallen@centerstreetlending.com"}}
    open newMessage
    

    set newMessage to make new outgoing message with properties {subject:"CSL Resale Advantage – Your Custom Referral Link", content:"Hey Austin,\r\rCheck out the new website here: https://www.centerstreetlending.com/resale-advantage\rThanks for joining the information session this week on the new CSL Resale Advantage program! \r\rBelow is your custom link to send to your borrowers:\r\rhttps://www.centerstreetlending.com/resale-advantage?rep=asteedman\r\rWhen a borrower uses your link, your information is automatically pushed through the form and marked in the system. As a backup, we can also always confirm you are the referral by communicating directly with Innovate Realty. \r\rIf you'd like to make a custom email signature with your URL, feel free to add it into your Signature block to get evergreen marketing for your referral link. \r\r*Example: Find out how CSL borrowers are getting 1% exclusive listing fees on their next sale. [Learn more here.]*\r\rIf you have any questions about the program or need additional info, please reach out directly to Suzanne or Paul:\r\rSuzanne Seini  \rInnovate Realty  \rsuzanne@innovaterealty.com  \r\r\r*— OR —*\r\r\rPaul Hanson  \rphanson@byebyehouse.com  \r\r\rThanks,\r\rGreg"}
    make new to recipient at newMessage with properties {email address:{address:"asteedman@centerstreetlending.com"}}
    open newMessage
    

    set newMessage to make new outgoing message with properties {subject:"CSL Resale Advantage – Your Custom Referral Link", content:"Hey Kara,\r\rCheck out the new website here: https://www.centerstreetlending.com/resale-advantage\rThanks for joining the information session this week on the new CSL Resale Advantage program! \r\rBelow is your custom link to send to your borrowers:\r\rhttps://www.centerstreetlending.com/resale-advantage?rep=karmstrong\r\rWhen a borrower uses your link, your information is automatically pushed through the form and marked in the system. As a backup, we can also always confirm you are the referral by communicating directly with Innovate Realty. \r\rIf you'd like to make a custom email signature with your URL, feel free to add it into your Signature block to get evergreen marketing for your referral link. \r\r*Example: Find out how CSL borrowers are getting 1% exclusive listing fees on their next sale. [Learn more here.]*\r\rIf you have any questions about the program or need additional info, please reach out directly to Suzanne or Paul:\r\rSuzanne Seini  \rInnovate Realty  \rsuzanne@innovaterealty.com  \r\r\r*— OR —*\r\r\rPaul Hanson  \rphanson@byebyehouse.com  \r\r\rThanks,\r\rGreg"}
    make new to recipient at newMessage with properties {email address:{address:"karmstrong@centerstreetlending.com"}}
    open newMessage
    

    set newMessage to make new outgoing message with properties {subject:"CSL Resale Advantage – Your Custom Referral Link", content:"Hey Max,\r\rCheck out the new website here: https://www.centerstreetlending.com/resale-advantage\rThanks for joining the information session this week on the new CSL Resale Advantage program! \r\rBelow is your custom link to send to your borrowers:\r\rhttps://www.centerstreetlending.com/resale-advantage?rep=mwoodyard\r\rWhen a borrower uses your link, your information is automatically pushed through the form and marked in the system. As a backup, we can also always confirm you are the referral by communicating directly with Innovate Realty. \r\rIf you'd like to make a custom email signature with your URL, feel free to add it into your Signature block to get evergreen marketing for your referral link. \r\r*Example: Find out how CSL borrowers are getting 1% exclusive listing fees on their next sale. [Learn more here.]*\r\rIf you have any questions about the program or need additional info, please reach out directly to Suzanne or Paul:\r\rSuzanne Seini  \rInnovate Realty  \rsuzanne@innovaterealty.com  \r\r\r*— OR —*\r\r\rPaul Hanson  \rphanson@byebyehouse.com  \r\r\rThanks,\r\rGreg"}
    make new to recipient at newMessage with properties {email address:{address:"mwoodyard@centerstreetlending.com"}}
    open newMessage
    

    set newMessage to make new outgoing message with properties {subject:"CSL Resale Advantage – Your Custom Referral Link", content:"Hey Michael,\r\rCheck out the new website here: https://www.centerstreetlending.com/resale-advantage\rThanks for joining the information session this week on the new CSL Resale Advantage program! \r\rBelow is your custom link to send to your borrowers:\r\rhttps://www.centerstreetlending.com/resale-advantage?rep=mprice\r\rWhen a borrower uses your link, your information is automatically pushed through the form and marked in the system. As a backup, we can also always confirm you are the referral by communicating directly with Innovate Realty. \r\rIf you'd like to make a custom email signature with your URL, feel free to add it into your Signature block to get evergreen marketing for your referral link. \r\r*Example: Find out how CSL borrowers are getting 1% exclusive listing fees on their next sale. [Learn more here.]*\r\rIf you have any questions about the program or need additional info, please reach out directly to Suzanne or Paul:\r\rSuzanne Seini  \rInnovate Realty  \rsuzanne@innovaterealty.com  \r\r\r*— OR —*\r\r\rPaul Hanson  \rphanson@byebyehouse.com  \r\r\rThanks,\r\rGreg"}
    make new to recipient at newMessage with properties {email address:{address:"mprice@centerstreetlending.com"}}
    open newMessage
    

    set newMessage to make new outgoing message with properties {subject:"CSL Resale Advantage – Your Custom Referral Link", content:"Hey Robert,\r\rCheck out the new website here: https://www.centerstreetlending.com/resale-advantage\rThanks for joining the information session this week on the new CSL Resale Advantage program! \r\rBelow is your custom link to send to your borrowers:\r\rhttps://www.centerstreetlending.com/resale-advantage?rep=rnewcomer\r\rWhen a borrower uses your link, your information is automatically pushed through the form and marked in the system. As a backup, we can also always confirm you are the referral by communicating directly with Innovate Realty. \r\rIf you'd like to make a custom email signature with your URL, feel free to add it into your Signature block to get evergreen marketing for your referral link. \r\r*Example: Find out how CSL borrowers are getting 1% exclusive listing fees on their next sale. [Learn more here.]*\r\rIf you have any questions about the program or need additional info, please reach out directly to Suzanne or Paul:\r\rSuzanne Seini  \rInnovate Realty  \rsuzanne@innovaterealty.com  \r\r\r*— OR —*\r\r\rPaul Hanson  \rphanson@byebyehouse.com  \r\r\rThanks,\r\rGreg"}
    make new to recipient at newMessage with properties {email address:{address:"rnewcomer@centerstreetlending.com"}}
    open newMessage
    

    set newMessage to make new outgoing message with properties {subject:"CSL Resale Advantage – Your Custom Referral Link", content:"Hey Sean,\r\rCheck out the new website here: https://www.centerstreetlending.com/resale-advantage\rThanks for joining the information session this week on the new CSL Resale Advantage program! \r\rBelow is your custom link to send to your borrowers:\r\rhttps://www.centerstreetlending.com/resale-advantage?rep=sburbidge\r\rWhen a borrower uses your link, your information is automatically pushed through the form and marked in the system. As a backup, we can also always confirm you are the referral by communicating directly with Innovate Realty. \r\rIf you'd like to make a custom email signature with your URL, feel free to add it into your Signature block to get evergreen marketing for your referral link. \r\r*Example: Find out how CSL borrowers are getting 1% exclusive listing fees on their next sale. [Learn more here.]*\r\rIf you have any questions about the program or need additional info, please reach out directly to Suzanne or Paul:\r\rSuzanne Seini  \rInnovate Realty  \rsuzanne@innovaterealty.com  \r\r\r*— OR —*\r\r\rPaul Hanson  \rphanson@byebyehouse.com  \r\r\rThanks,\r\rGreg"}
    make new to recipient at newMessage with properties {email address:{address:"sburbidge@centerstreetlending.com"}}
    open newMessage
    

    set newMessage to make new outgoing message with properties {subject:"CSL Resale Advantage – Your Custom Referral Link", content:"Hey Dallin,\r\rCheck out the new website here: https://www.centerstreetlending.com/resale-advantage\rThanks for joining the information session this week on the new CSL Resale Advantage program! \r\rBelow is your custom link to send to your borrowers:\r\rhttps://www.centerstreetlending.com/resale-advantage?rep=dwaldvogel\r\rWhen a borrower uses your link, your information is automatically pushed through the form and marked in the system. As a backup, we can also always confirm you are the referral by communicating directly with Innovate Realty. \r\rIf you'd like to make a custom email signature with your URL, feel free to add it into your Signature block to get evergreen marketing for your referral link. \r\r*Example: Find out how CSL borrowers are getting 1% exclusive listing fees on their next sale. [Learn more here.]*\r\rIf you have any questions about the program or need additional info, please reach out directly to Suzanne or Paul:\r\rSuzanne Seini  \rInnovate Realty  \rsuzanne@innovaterealty.com  \r\r\r*— OR —*\r\r\rPaul Hanson  \rphanson@byebyehouse.com  \r\r\rThanks,\r\rGreg"}
    make new to recipient at newMessage with properties {email address:{address:"dwaldvogel@centerstreetlending.com"}}
    open newMessage
    

    set newMessage to make new outgoing message with properties {subject:"CSL Resale Advantage – Your Custom Referral Link", content:"Hey Ford,\r\rCheck out the new website here: https://www.centerstreetlending.com/resale-advantage\rThanks for joining the information session this week on the new CSL Resale Advantage program! \r\rBelow is your custom link to send to your borrowers:\r\rhttps://www.centerstreetlending.com/resale-advantage?rep=ffairon\r\rWhen a borrower uses your link, your information is automatically pushed through the form and marked in the system. As a backup, we can also always confirm you are the referral by communicating directly with Innovate Realty. \r\rIf you'd like to make a custom email signature with your URL, feel free to add it into your Signature block to get evergreen marketing for your referral link. \r\r*Example: Find out how CSL borrowers are getting 1% exclusive listing fees on their next sale. [Learn more here.]*\r\rIf you have any questions about the program or need additional info, please reach out directly to Suzanne or Paul:\r\rSuzanne Seini  \rInnovate Realty  \rsuzanne@innovaterealty.com  \r\r\r*— OR —*\r\r\rPaul Hanson  \rphanson@byebyehouse.com  \r\r\rThanks,\r\rGreg"}
    make new to recipient at newMessage with properties {email address:{address:"ffairon@centerstreetlending.com"}}
    open newMessage
    

    set newMessage to make new outgoing message with properties {subject:"CSL Resale Advantage – Your Custom Referral Link", content:"Hey Guy,\r\rCheck out the new website here: https://www.centerstreetlending.com/resale-advantage\rThanks for joining the information session this week on the new CSL Resale Advantage program! \r\rBelow is your custom link to send to your borrowers:\r\rhttps://www.centerstreetlending.com/resale-advantage?rep=gclauss\r\rWhen a borrower uses your link, your information is automatically pushed through the form and marked in the system. As a backup, we can also always confirm you are the referral by communicating directly with Innovate Realty. \r\rIf you'd like to make a custom email signature with your URL, feel free to add it into your Signature block to get evergreen marketing for your referral link. \r\r*Example: Find out how CSL borrowers are getting 1% exclusive listing fees on their next sale. [Learn more here.]*\r\rIf you have any questions about the program or need additional info, please reach out directly to Suzanne or Paul:\r\rSuzanne Seini  \rInnovate Realty  \rsuzanne@innovaterealty.com  \r\r\r*— OR —*\r\r\rPaul Hanson  \rphanson@byebyehouse.com  \r\r\rThanks,\r\rGreg"}
    make new to recipient at newMessage with properties {email address:{address:"gclauss@centerstreetlending.com"}}
    open newMessage
    

    set newMessage to make new outgoing message with properties {subject:"CSL Resale Advantage – Your Custom Referral Link", content:"Hey Jack,\r\rCheck out the new website here: https://www.centerstreetlending.com/resale-advantage\rThanks for joining the information session this week on the new CSL Resale Advantage program! \r\rBelow is your custom link to send to your borrowers:\r\rhttps://www.centerstreetlending.com/resale-advantage?rep=jguenther\r\rWhen a borrower uses your link, your information is automatically pushed through the form and marked in the system. As a backup, we can also always confirm you are the referral by communicating directly with Innovate Realty. \r\rIf you'd like to make a custom email signature with your URL, feel free to add it into your Signature block to get evergreen marketing for your referral link. \r\r*Example: Find out how CSL borrowers are getting 1% exclusive listing fees on their next sale. [Learn more here.]*\r\rIf you have any questions about the program or need additional info, please reach out directly to Suzanne or Paul:\r\rSuzanne Seini  \rInnovate Realty  \rsuzanne@innovaterealty.com  \r\r\r*— OR —*\r\r\rPaul Hanson  \rphanson@byebyehouse.com  \r\r\rThanks,\r\rGreg"}
    make new to recipient at newMessage with properties {email address:{address:"jguenther@centerstreetlending.com"}}
    open newMessage
    

    set newMessage to make new outgoing message with properties {subject:"CSL Resale Advantage – Your Custom Referral Link", content:"Hey Ryan,\r\rCheck out the new website here: https://www.centerstreetlending.com/resale-advantage\rThanks for joining the information session this week on the new CSL Resale Advantage program! \r\rBelow is your custom link to send to your borrowers:\r\rhttps://www.centerstreetlending.com/resale-advantage?rep=rclayton\r\rWhen a borrower uses your link, your information is automatically pushed through the form and marked in the system. As a backup, we can also always confirm you are the referral by communicating directly with Innovate Realty. \r\rIf you'd like to make a custom email signature with your URL, feel free to add it into your Signature block to get evergreen marketing for your referral link. \r\r*Example: Find out how CSL borrowers are getting 1% exclusive listing fees on their next sale. [Learn more here.]*\r\rIf you have any questions about the program or need additional info, please reach out directly to Suzanne or Paul:\r\rSuzanne Seini  \rInnovate Realty  \rsuzanne@innovaterealty.com  \r\r\r*— OR —*\r\r\rPaul Hanson  \rphanson@byebyehouse.com  \r\r\rThanks,\r\rGreg"}
    make new to recipient at newMessage with properties {email address:{address:"rclayton@centerstreetlending.com"}}
    open newMessage
    

    set newMessage to make new outgoing message with properties {subject:"CSL Resale Advantage – Your Custom Referral Link", content:"Hey Sean,\r\rCheck out the new website here: https://www.centerstreetlending.com/resale-advantage\rThanks for joining the information session this week on the new CSL Resale Advantage program! \r\rBelow is your custom link to send to your borrowers:\r\rhttps://www.centerstreetlending.com/resale-advantage?rep=sklement\r\rWhen a borrower uses your link, your information is automatically pushed through the form and marked in the system. As a backup, we can also always confirm you are the referral by communicating directly with Innovate Realty. \r\rIf you'd like to make a custom email signature with your URL, feel free to add it into your Signature block to get evergreen marketing for your referral link. \r\r*Example: Find out how CSL borrowers are getting 1% exclusive listing fees on their next sale. [Learn more here.]*\r\rIf you have any questions about the program or need additional info, please reach out directly to Suzanne or Paul:\r\rSuzanne Seini  \rInnovate Realty  \rsuzanne@innovaterealty.com  \r\r\r*— OR —*\r\r\rPaul Hanson  \rphanson@byebyehouse.com  \r\r\rThanks,\r\rGreg"}
    make new to recipient at newMessage with properties {email address:{address:"sklement@centerstreetlending.com"}}
    open newMessage
    

    set newMessage to make new outgoing message with properties {subject:"CSL Resale Advantage – Your Custom Referral Link", content:"Hey Brandon,\r\rCheck out the new website here: https://www.centerstreetlending.com/resale-advantage\rThanks for joining the information session this week on the new CSL Resale Advantage program! \r\rBelow is your custom link to send to your borrowers:\r\rhttps://www.centerstreetlending.com/resale-advantage?rep=bherbert\r\rWhen a borrower uses your link, your information is automatically pushed through the form and marked in the system. As a backup, we can also always confirm you are the referral by communicating directly with Innovate Realty. \r\rIf you'd like to make a custom email signature with your URL, feel free to add it into your Signature block to get evergreen marketing for your referral link. \r\r*Example: Find out how CSL borrowers are getting 1% exclusive listing fees on their next sale. [Learn more here.]*\r\rIf you have any questions about the program or need additional info, please reach out directly to Suzanne or Paul:\r\rSuzanne Seini  \rInnovate Realty  \rsuzanne@innovaterealty.com  \r\r\r*— OR —*\r\r\rPaul Hanson  \rphanson@byebyehouse.com  \r\r\rThanks,\r\rGreg"}
    make new to recipient at newMessage with properties {email address:{address:"bherbert@centerstreetlending.com"}}
    open newMessage
    

    set newMessage to make new outgoing message with properties {subject:"CSL Resale Advantage – Your Custom Referral Link", content:"Hey Crystal,\r\rCheck out the new website here: https://www.centerstreetlending.com/resale-advantage\rThanks for joining the information session this week on the new CSL Resale Advantage program! \r\rBelow is your custom link to send to your borrowers:\r\rhttps://www.centerstreetlending.com/resale-advantage?rep=cmora\r\rWhen a borrower uses your link, your information is automatically pushed through the form and marked in the system. As a backup, we can also always confirm you are the referral by communicating directly with Innovate Realty. \r\rIf you'd like to make a custom email signature with your URL, feel free to add it into your Signature block to get evergreen marketing for your referral link. \r\r*Example: Find out how CSL borrowers are getting 1% exclusive listing fees on their next sale. [Learn more here.]*\r\rIf you have any questions about the program or need additional info, please reach out directly to Suzanne or Paul:\r\rSuzanne Seini  \rInnovate Realty  \rsuzanne@innovaterealty.com  \r\r\r*— OR —*\r\r\rPaul Hanson  \rphanson@byebyehouse.com  \r\r\rThanks,\r\rGreg"}
    make new to recipient at newMessage with properties {email address:{address:"cmora@centerstreetlending.com"}}
    open newMessage
    

    set newMessage to make new outgoing message with properties {subject:"CSL Resale Advantage – Your Custom Referral Link", content:"Hey Jacob,\r\rCheck out the new website here: https://www.centerstreetlending.com/resale-advantage\rThanks for joining the information session this week on the new CSL Resale Advantage program! \r\rBelow is your custom link to send to your borrowers:\r\rhttps://www.centerstreetlending.com/resale-advantage?rep=jwoodyard\r\rWhen a borrower uses your link, your information is automatically pushed through the form and marked in the system. As a backup, we can also always confirm you are the referral by communicating directly with Innovate Realty. \r\rIf you'd like to make a custom email signature with your URL, feel free to add it into your Signature block to get evergreen marketing for your referral link. \r\r*Example: Find out how CSL borrowers are getting 1% exclusive listing fees on their next sale. [Learn more here.]*\r\rIf you have any questions about the program or need additional info, please reach out directly to Suzanne or Paul:\r\rSuzanne Seini  \rInnovate Realty  \rsuzanne@innovaterealty.com  \r\r\r*— OR —*\r\r\rPaul Hanson  \rphanson@byebyehouse.com  \r\r\rThanks,\r\rGreg"}
    make new to recipient at newMessage with properties {email address:{address:"jwoodyard@centerstreetlending.com"}}
    open newMessage
    

    set newMessage to make new outgoing message with properties {subject:"CSL Resale Advantage – Your Custom Referral Link", content:"Hey Lauren,\r\rCheck out the new website here: https://www.centerstreetlending.com/resale-advantage\rThanks for joining the information session this week on the new CSL Resale Advantage program! \r\rBelow is your custom link to send to your borrowers:\r\rhttps://www.centerstreetlending.com/resale-advantage?rep=llipinski\r\rWhen a borrower uses your link, your information is automatically pushed through the form and marked in the system. As a backup, we can also always confirm you are the referral by communicating directly with Innovate Realty. \r\rIf you'd like to make a custom email signature with your URL, feel free to add it into your Signature block to get evergreen marketing for your referral link. \r\r*Example: Find out how CSL borrowers are getting 1% exclusive listing fees on their next sale. [Learn more here.]*\r\rIf you have any questions about the program or need additional info, please reach out directly to Suzanne or Paul:\r\rSuzanne Seini  \rInnovate Realty  \rsuzanne@innovaterealty.com  \r\r\r*— OR —*\r\r\rPaul Hanson  \rphanson@byebyehouse.com  \r\r\rThanks,\r\rGreg"}
    make new to recipient at newMessage with properties {email address:{address:"llipinski@centerstreetlending.com"}}
    open newMessage
    

    set newMessage to make new outgoing message with properties {subject:"CSL Resale Advantage – Your Custom Referral Link", content:"Hey Richard,\r\rCheck out the new website here: https://www.centerstreetlending.com/resale-advantage\rThanks for joining the information session this week on the new CSL Resale Advantage program! \r\rBelow is your custom link to send to your borrowers:\r\rhttps://www.centerstreetlending.com/resale-advantage?rep=rkim\r\rWhen a borrower uses your link, your information is automatically pushed through the form and marked in the system. As a backup, we can also always confirm you are the referral by communicating directly with Innovate Realty. \r\rIf you'd like to make a custom email signature with your URL, feel free to add it into your Signature block to get evergreen marketing for your referral link. \r\r*Example: Find out how CSL borrowers are getting 1% exclusive listing fees on their next sale. [Learn more here.]*\r\rIf you have any questions about the program or need additional info, please reach out directly to Suzanne or Paul:\r\rSuzanne Seini  \rInnovate Realty  \rsuzanne@innovaterealty.com  \r\r\r*— OR —*\r\r\rPaul Hanson  \rphanson@byebyehouse.com  \r\r\rThanks,\r\rGreg"}
    make new to recipient at newMessage with properties {email address:{address:"rkim@centerstreetlending.com"}}
    open newMessage
    

    set newMessage to make new outgoing message with properties {subject:"CSL Resale Advantage – Your Custom Referral Link", content:"Hey Trevor,\r\rCheck out the new website here: https://www.centerstreetlending.com/resale-advantage\rThanks for joining the information session this week on the new CSL Resale Advantage program! \r\rBelow is your custom link to send to your borrowers:\r\rhttps://www.centerstreetlending.com/resale-advantage?rep=tburbidge\r\rWhen a borrower uses your link, your information is automatically pushed through the form and marked in the system. As a backup, we can also always confirm you are the referral by communicating directly with Innovate Realty. \r\rIf you'd like to make a custom email signature with your URL, feel free to add it into your Signature block to get evergreen marketing for your referral link. \r\r*Example: Find out how CSL borrowers are getting 1% exclusive listing fees on their next sale. [Learn more here.]*\r\rIf you have any questions about the program or need additional info, please reach out directly to Suzanne or Paul:\r\rSuzanne Seini  \rInnovate Realty  \rsuzanne@innovaterealty.com  \r\r\r*— OR —*\r\r\rPaul Hanson  \rphanson@byebyehouse.com  \r\r\rThanks,\r\rGreg"}
    make new to recipient at newMessage with properties {email address:{address:"tburbidge@centerstreetlending.com"}}
    open newMessage
    

    set newMessage to make new outgoing message with properties {subject:"CSL Resale Advantage – Your Custom Referral Link", content:"Hey Jacob,\r\rCheck out the new website here: https://www.centerstreetlending.com/resale-advantage\rThanks for joining the information session this week on the new CSL Resale Advantage program! \r\rBelow is your custom link to send to your borrowers:\r\rhttps://www.centerstreetlending.com/resale-advantage?rep=jcho\r\rWhen a borrower uses your link, your information is automatically pushed through the form and marked in the system. As a backup, we can also always confirm you are the referral by communicating directly with Innovate Realty. \r\rIf you'd like to make a custom email signature with your URL, feel free to add it into your Signature block to get evergreen marketing for your referral link. \r\r*Example: Find out how CSL borrowers are getting 1% exclusive listing fees on their next sale. [Learn more here.]*\r\rIf you have any questions about the program or need additional info, please reach out directly to Suzanne or Paul:\r\rSuzanne Seini  \rInnovate Realty  \rsuzanne@innovaterealty.com  \r\r\r*— OR —*\r\r\rPaul Hanson  \rphanson@byebyehouse.com  \r\r\rThanks,\r\rGreg"}
    make new to recipient at newMessage with properties {email address:{address:"jcho@centerstreetlending.com"}}
    open newMessage
    
end tell