tell application "Microsoft Outlook"

    set newMessage to make new outgoing message with properties {subject:"CSL Resale Advantage – Your Custom Referral Link", content:"Hey Alec,<br><br>Check out the new website here: <a href=\"https://www.centerstreetlending.com/resale-advantage\">https://www.centerstreetlending.com/resale-advantage</a><br>Thanks for joining the information session this week on the new CSL Resale Advantage program!<br><br>Below is your custom link to send to your borrowers:<br><br><strong><a href=\"https://www.centerstreetlending.com/resale-advantage?rep=aralph\">https://www.centerstreetlending.com/resale-advantage?rep=aralph</a></strong><br><br>When a borrower uses your link, your information is automatically pushed through the form and marked in the system. As a backup, we can also always confirm you are the referral by communicating directly with Innovate Realty.<br><br><strong>If you'd like to make a custom email signature with your URL, feel free to add it into your Signature block to get evergreen marketing for your referral link.</strong><br><br><em>Example: Find out how CSL borrowers are getting 1% exclusive listing fees on their next sale. [Learn more here.]</em><br><br>If you have any questions about the program or need additional info, please reach out directly to Suzanne or Paul:<br><br><strong>Suzanne Seini</strong><br>Innovate Realty<br>suzanne@innovaterealty.com<br><em>— OR —</em><br><strong>Paul Hanson</strong><br>phanson@byebyehouse.com"}
    make new to recipient at newMessage with properties {email address:{address:"aralph@centerstreetlending.com"}}
    open newMessage
    

    set newMessage to make new outgoing message with properties {subject:"CSL Resale Advantage – Your Custom Referral Link", content:"Hey Allyssa,<br><br>Check out the new website here: <a href=\"https://www.centerstreetlending.com/resale-advantage\">https://www.centerstreetlending.com/resale-advantage</a><br>Thanks for joining the information session this week on the new CSL Resale Advantage program!<br><br>Below is your custom link to send to your borrowers:<br><br><strong><a href=\"https://www.centerstreetlending.com/resale-advantage?rep=amichaelson\">https://www.centerstreetlending.com/resale-advantage?rep=amichaelson</a></strong><br><br>When a borrower uses your link, your information is automatically pushed through the form and marked in the system. As a backup, we can also always confirm you are the referral by communicating directly with Innovate Realty.<br><br><strong>If you'd like to make a custom email signature with your URL, feel free to add it into your Signature block to get evergreen marketing for your referral link.</strong><br><br><em>Example: Find out how CSL borrowers are getting 1% exclusive listing fees on their next sale. [Learn more here.]</em><br><br>If you have any questions about the program or need additional info, please reach out directly to Suzanne or Paul:<br><br><strong>Suzanne Seini</strong><br>Innovate Realty<br>suzanne@innovaterealty.com<br><em>— OR —</em><br><strong>Paul Hanson</strong><br>phanson@byebyehouse.com"}
    make new to recipient at newMessage with properties {email address:{address:"amichaelson@centerstreetlending.com"}}
    open newMessage
    

    set newMessage to make new outgoing message with properties {subject:"CSL Resale Advantage – Your Custom Referral Link", content:"Hey Angelica,<br><br>Check out the new website here: <a href=\"https://www.centerstreetlending.com/resale-advantage\">https://www.centerstreetlending.com/resale-advantage</a><br>Thanks for joining the information session this week on the new CSL Resale Advantage program!<br><br>Below is your custom link to send to your borrowers:<br><br><strong><a href=\"https://www.centerstreetlending.com/resale-advantage?rep=anaranjo\">https://www.centerstreetlending.com/resale-advantage?rep=anaranjo</a></strong><br><br>When a borrower uses your link, your information is automatically pushed through the form and marked in the system. As a backup, we can also always confirm you are the referral by communicating directly with Innovate Realty.<br><br><strong>If you'd like to make a custom email signature with your URL, feel free to add it into your Signature block to get evergreen marketing for your referral link.</strong><br><br><em>Example: Find out how CSL borrowers are getting 1% exclusive listing fees on their next sale. [Learn more here.]</em><br><br>If you have any questions about the program or need additional info, please reach out directly to Suzanne or Paul:<br><br><strong>Suzanne Seini</strong><br>Innovate Realty<br>suzanne@innovaterealty.com<br><em>— OR —</em><br><strong>Paul Hanson</strong><br>phanson@byebyehouse.com"}
    make new to recipient at newMessage with properties {email address:{address:"anaranjo@centerstreetlending.com"}}
    open newMessage
    

    set newMessage to make new outgoing message with properties {subject:"CSL Resale Advantage – Your Custom Referral Link", content:"Hey Christine,<br><br>Check out the new website here: <a href=\"https://www.centerstreetlending.com/resale-advantage\">https://www.centerstreetlending.com/resale-advantage</a><br>Thanks for joining the information session this week on the new CSL Resale Advantage program!<br><br>Below is your custom link to send to your borrowers:<br><br><strong><a href=\"https://www.centerstreetlending.com/resale-advantage?rep=cflores\">https://www.centerstreetlending.com/resale-advantage?rep=cflores</a></strong><br><br>When a borrower uses your link, your information is automatically pushed through the form and marked in the system. As a backup, we can also always confirm you are the referral by communicating directly with Innovate Realty.<br><br><strong>If you'd like to make a custom email signature with your URL, feel free to add it into your Signature block to get evergreen marketing for your referral link.</strong><br><br><em>Example: Find out how CSL borrowers are getting 1% exclusive listing fees on their next sale. [Learn more here.]</em><br><br>If you have any questions about the program or need additional info, please reach out directly to Suzanne or Paul:<br><br><strong>Suzanne Seini</strong><br>Innovate Realty<br>suzanne@innovaterealty.com<br><em>— OR —</em><br><strong>Paul Hanson</strong><br>phanson@byebyehouse.com"}
    make new to recipient at newMessage with properties {email address:{address:"cflores@centerstreetlending.com"}}
    open newMessage
    

    set newMessage to make new outgoing message with properties {subject:"CSL Resale Advantage – Your Custom Referral Link", content:"Hey Daniel,<br><br>Check out the new website here: <a href=\"https://www.centerstreetlending.com/resale-advantage\">https://www.centerstreetlending.com/resale-advantage</a><br>Thanks for joining the information session this week on the new CSL Resale Advantage program!<br><br>Below is your custom link to send to your borrowers:<br><br><strong><a href=\"https://www.centerstreetlending.com/resale-advantage?rep=dayache\">https://www.centerstreetlending.com/resale-advantage?rep=dayache</a></strong><br><br>When a borrower uses your link, your information is automatically pushed through the form and marked in the system. As a backup, we can also always confirm you are the referral by communicating directly with Innovate Realty.<br><br><strong>If you'd like to make a custom email signature with your URL, feel free to add it into your Signature block to get evergreen marketing for your referral link.</strong><br><br><em>Example: Find out how CSL borrowers are getting 1% exclusive listing fees on their next sale. [Learn more here.]</em><br><br>If you have any questions about the program or need additional info, please reach out directly to Suzanne or Paul:<br><br><strong>Suzanne Seini</strong><br>Innovate Realty<br>suzanne@innovaterealty.com<br><em>— OR —</em><br><strong>Paul Hanson</strong><br>phanson@byebyehouse.com"}
    make new to recipient at newMessage with properties {email address:{address:"dayache@centerstreetlending.com"}}
    open newMessage
    

    set newMessage to make new outgoing message with properties {subject:"CSL Resale Advantage – Your Custom Referral Link", content:"Hey Diana,<br><br>Check out the new website here: <a href=\"https://www.centerstreetlending.com/resale-advantage\">https://www.centerstreetlending.com/resale-advantage</a><br>Thanks for joining the information session this week on the new CSL Resale Advantage program!<br><br>Below is your custom link to send to your borrowers:<br><br><strong><a href=\"https://www.centerstreetlending.com/resale-advantage?rep=dsmith\">https://www.centerstreetlending.com/resale-advantage?rep=dsmith</a></strong><br><br>When a borrower uses your link, your information is automatically pushed through the form and marked in the system. As a backup, we can also always confirm you are the referral by communicating directly with Innovate Realty.<br><br><strong>If you'd like to make a custom email signature with your URL, feel free to add it into your Signature block to get evergreen marketing for your referral link.</strong><br><br><em>Example: Find out how CSL borrowers are getting 1% exclusive listing fees on their next sale. [Learn more here.]</em><br><br>If you have any questions about the program or need additional info, please reach out directly to Suzanne or Paul:<br><br><strong>Suzanne Seini</strong><br>Innovate Realty<br>suzanne@innovaterealty.com<br><em>— OR —</em><br><strong>Paul Hanson</strong><br>phanson@byebyehouse.com"}
    make new to recipient at newMessage with properties {email address:{address:"dsmith@centerstreetlending.com"}}
    open newMessage
    

    set newMessage to make new outgoing message with properties {subject:"CSL Resale Advantage – Your Custom Referral Link", content:"Hey Jeremy,<br><br>Check out the new website here: <a href=\"https://www.centerstreetlending.com/resale-advantage\">https://www.centerstreetlending.com/resale-advantage</a><br>Thanks for joining the information session this week on the new CSL Resale Advantage program!<br><br>Below is your custom link to send to your borrowers:<br><br><strong><a href=\"https://www.centerstreetlending.com/resale-advantage?rep=jmullins\">https://www.centerstreetlending.com/resale-advantage?rep=jmullins</a></strong><br><br>When a borrower uses your link, your information is automatically pushed through the form and marked in the system. As a backup, we can also always confirm you are the referral by communicating directly with Innovate Realty.<br><br><strong>If you'd like to make a custom email signature with your URL, feel free to add it into your Signature block to get evergreen marketing for your referral link.</strong><br><br><em>Example: Find out how CSL borrowers are getting 1% exclusive listing fees on their next sale. [Learn more here.]</em><br><br>If you have any questions about the program or need additional info, please reach out directly to Suzanne or Paul:<br><br><strong>Suzanne Seini</strong><br>Innovate Realty<br>suzanne@innovaterealty.com<br><em>— OR —</em><br><strong>Paul Hanson</strong><br>phanson@byebyehouse.com"}
    make new to recipient at newMessage with properties {email address:{address:"jmullins@centerstreetlending.com"}}
    open newMessage
    

    set newMessage to make new outgoing message with properties {subject:"CSL Resale Advantage – Your Custom Referral Link", content:"Hey Kevin,<br><br>Check out the new website here: <a href=\"https://www.centerstreetlending.com/resale-advantage\">https://www.centerstreetlending.com/resale-advantage</a><br>Thanks for joining the information session this week on the new CSL Resale Advantage program!<br><br>Below is your custom link to send to your borrowers:<br><br><strong><a href=\"https://www.centerstreetlending.com/resale-advantage?rep=kmartinez\">https://www.centerstreetlending.com/resale-advantage?rep=kmartinez</a></strong><br><br>When a borrower uses your link, your information is automatically pushed through the form and marked in the system. As a backup, we can also always confirm you are the referral by communicating directly with Innovate Realty.<br><br><strong>If you'd like to make a custom email signature with your URL, feel free to add it into your Signature block to get evergreen marketing for your referral link.</strong><br><br><em>Example: Find out how CSL borrowers are getting 1% exclusive listing fees on their next sale. [Learn more here.]</em><br><br>If you have any questions about the program or need additional info, please reach out directly to Suzanne or Paul:<br><br><strong>Suzanne Seini</strong><br>Innovate Realty<br>suzanne@innovaterealty.com<br><em>— OR —</em><br><strong>Paul Hanson</strong><br>phanson@byebyehouse.com"}
    make new to recipient at newMessage with properties {email address:{address:"kmartinez@centerstreetlending.com"}}
    open newMessage
    

    set newMessage to make new outgoing message with properties {subject:"CSL Resale Advantage – Your Custom Referral Link", content:"Hey Luis,<br><br>Check out the new website here: <a href=\"https://www.centerstreetlending.com/resale-advantage\">https://www.centerstreetlending.com/resale-advantage</a><br>Thanks for joining the information session this week on the new CSL Resale Advantage program!<br><br>Below is your custom link to send to your borrowers:<br><br><strong><a href=\"https://www.centerstreetlending.com/resale-advantage?rep=lmontero\">https://www.centerstreetlending.com/resale-advantage?rep=lmontero</a></strong><br><br>When a borrower uses your link, your information is automatically pushed through the form and marked in the system. As a backup, we can also always confirm you are the referral by communicating directly with Innovate Realty.<br><br><strong>If you'd like to make a custom email signature with your URL, feel free to add it into your Signature block to get evergreen marketing for your referral link.</strong><br><br><em>Example: Find out how CSL borrowers are getting 1% exclusive listing fees on their next sale. [Learn more here.]</em><br><br>If you have any questions about the program or need additional info, please reach out directly to Suzanne or Paul:<br><br><strong>Suzanne Seini</strong><br>Innovate Realty<br>suzanne@innovaterealty.com<br><em>— OR —</em><br><strong>Paul Hanson</strong><br>phanson@byebyehouse.com"}
    make new to recipient at newMessage with properties {email address:{address:"lmontero@centerstreetlending.com"}}
    open newMessage
    

    set newMessage to make new outgoing message with properties {subject:"CSL Resale Advantage – Your Custom Referral Link", content:"Hey Marlena,<br><br>Check out the new website here: <a href=\"https://www.centerstreetlending.com/resale-advantage\">https://www.centerstreetlending.com/resale-advantage</a><br>Thanks for joining the information session this week on the new CSL Resale Advantage program!<br><br>Below is your custom link to send to your borrowers:<br><br><strong><a href=\"https://www.centerstreetlending.com/resale-advantage?rep=mlacourse\">https://www.centerstreetlending.com/resale-advantage?rep=mlacourse</a></strong><br><br>When a borrower uses your link, your information is automatically pushed through the form and marked in the system. As a backup, we can also always confirm you are the referral by communicating directly with Innovate Realty.<br><br><strong>If you'd like to make a custom email signature with your URL, feel free to add it into your Signature block to get evergreen marketing for your referral link.</strong><br><br><em>Example: Find out how CSL borrowers are getting 1% exclusive listing fees on their next sale. [Learn more here.]</em><br><br>If you have any questions about the program or need additional info, please reach out directly to Suzanne or Paul:<br><br><strong>Suzanne Seini</strong><br>Innovate Realty<br>suzanne@innovaterealty.com<br><em>— OR —</em><br><strong>Paul Hanson</strong><br>phanson@byebyehouse.com"}
    make new to recipient at newMessage with properties {email address:{address:"mlacourse@centerstreetlending.com"}}
    open newMessage
    

    set newMessage to make new outgoing message with properties {subject:"CSL Resale Advantage – Your Custom Referral Link", content:"Hey Richard,<br><br>Check out the new website here: <a href=\"https://www.centerstreetlending.com/resale-advantage\">https://www.centerstreetlending.com/resale-advantage</a><br>Thanks for joining the information session this week on the new CSL Resale Advantage program!<br><br>Below is your custom link to send to your borrowers:<br><br><strong><a href=\"https://www.centerstreetlending.com/resale-advantage?rep=rvu\">https://www.centerstreetlending.com/resale-advantage?rep=rvu</a></strong><br><br>When a borrower uses your link, your information is automatically pushed through the form and marked in the system. As a backup, we can also always confirm you are the referral by communicating directly with Innovate Realty.<br><br><strong>If you'd like to make a custom email signature with your URL, feel free to add it into your Signature block to get evergreen marketing for your referral link.</strong><br><br><em>Example: Find out how CSL borrowers are getting 1% exclusive listing fees on their next sale. [Learn more here.]</em><br><br>If you have any questions about the program or need additional info, please reach out directly to Suzanne or Paul:<br><br><strong>Suzanne Seini</strong><br>Innovate Realty<br>suzanne@innovaterealty.com<br><em>— OR —</em><br><strong>Paul Hanson</strong><br>phanson@byebyehouse.com"}
    make new to recipient at newMessage with properties {email address:{address:"rvu@centerstreetlending.com"}}
    open newMessage
    

    set newMessage to make new outgoing message with properties {subject:"CSL Resale Advantage – Your Custom Referral Link", content:"Hey Ryan,<br><br>Check out the new website here: <a href=\"https://www.centerstreetlending.com/resale-advantage\">https://www.centerstreetlending.com/resale-advantage</a><br>Thanks for joining the information session this week on the new CSL Resale Advantage program!<br><br>Below is your custom link to send to your borrowers:<br><br><strong><a href=\"https://www.centerstreetlending.com/resale-advantage?rep=rguerrero\">https://www.centerstreetlending.com/resale-advantage?rep=rguerrero</a></strong><br><br>When a borrower uses your link, your information is automatically pushed through the form and marked in the system. As a backup, we can also always confirm you are the referral by communicating directly with Innovate Realty.<br><br><strong>If you'd like to make a custom email signature with your URL, feel free to add it into your Signature block to get evergreen marketing for your referral link.</strong><br><br><em>Example: Find out how CSL borrowers are getting 1% exclusive listing fees on their next sale. [Learn more here.]</em><br><br>If you have any questions about the program or need additional info, please reach out directly to Suzanne or Paul:<br><br><strong>Suzanne Seini</strong><br>Innovate Realty<br>suzanne@innovaterealty.com<br><em>— OR —</em><br><strong>Paul Hanson</strong><br>phanson@byebyehouse.com"}
    make new to recipient at newMessage with properties {email address:{address:"rguerrero@centerstreetlending.com"}}
    open newMessage
    

    set newMessage to make new outgoing message with properties {subject:"CSL Resale Advantage – Your Custom Referral Link", content:"Hey Sherif,<br><br>Check out the new website here: <a href=\"https://www.centerstreetlending.com/resale-advantage\">https://www.centerstreetlending.com/resale-advantage</a><br>Thanks for joining the information session this week on the new CSL Resale Advantage program!<br><br>Below is your custom link to send to your borrowers:<br><br><strong><a href=\"https://www.centerstreetlending.com/resale-advantage?rep=shashem\">https://www.centerstreetlending.com/resale-advantage?rep=shashem</a></strong><br><br>When a borrower uses your link, your information is automatically pushed through the form and marked in the system. As a backup, we can also always confirm you are the referral by communicating directly with Innovate Realty.<br><br><strong>If you'd like to make a custom email signature with your URL, feel free to add it into your Signature block to get evergreen marketing for your referral link.</strong><br><br><em>Example: Find out how CSL borrowers are getting 1% exclusive listing fees on their next sale. [Learn more here.]</em><br><br>If you have any questions about the program or need additional info, please reach out directly to Suzanne or Paul:<br><br><strong>Suzanne Seini</strong><br>Innovate Realty<br>suzanne@innovaterealty.com<br><em>— OR —</em><br><strong>Paul Hanson</strong><br>phanson@byebyehouse.com"}
    make new to recipient at newMessage with properties {email address:{address:"shashem@centerstreetlending.com"}}
    open newMessage
    

    set newMessage to make new outgoing message with properties {subject:"CSL Resale Advantage – Your Custom Referral Link", content:"Hey Erik,<br><br>Check out the new website here: <a href=\"https://www.centerstreetlending.com/resale-advantage\">https://www.centerstreetlending.com/resale-advantage</a><br>Thanks for joining the information session this week on the new CSL Resale Advantage program!<br><br>Below is your custom link to send to your borrowers:<br><br><strong><a href=\"https://www.centerstreetlending.com/resale-advantage?rep=ebrown\">https://www.centerstreetlending.com/resale-advantage?rep=ebrown</a></strong><br><br>When a borrower uses your link, your information is automatically pushed through the form and marked in the system. As a backup, we can also always confirm you are the referral by communicating directly with Innovate Realty.<br><br><strong>If you'd like to make a custom email signature with your URL, feel free to add it into your Signature block to get evergreen marketing for your referral link.</strong><br><br><em>Example: Find out how CSL borrowers are getting 1% exclusive listing fees on their next sale. [Learn more here.]</em><br><br>If you have any questions about the program or need additional info, please reach out directly to Suzanne or Paul:<br><br><strong>Suzanne Seini</strong><br>Innovate Realty<br>suzanne@innovaterealty.com<br><em>— OR —</em><br><strong>Paul Hanson</strong><br>phanson@byebyehouse.com"}
    make new to recipient at newMessage with properties {email address:{address:"ebrown@centerstreetlending.com"}}
    open newMessage
    

    set newMessage to make new outgoing message with properties {subject:"CSL Resale Advantage – Your Custom Referral Link", content:"Hey Jeremiah,<br><br>Check out the new website here: <a href=\"https://www.centerstreetlending.com/resale-advantage\">https://www.centerstreetlending.com/resale-advantage</a><br>Thanks for joining the information session this week on the new CSL Resale Advantage program!<br><br>Below is your custom link to send to your borrowers:<br><br><strong><a href=\"https://www.centerstreetlending.com/resale-advantage?rep=jwiedman\">https://www.centerstreetlending.com/resale-advantage?rep=jwiedman</a></strong><br><br>When a borrower uses your link, your information is automatically pushed through the form and marked in the system. As a backup, we can also always confirm you are the referral by communicating directly with Innovate Realty.<br><br><strong>If you'd like to make a custom email signature with your URL, feel free to add it into your Signature block to get evergreen marketing for your referral link.</strong><br><br><em>Example: Find out how CSL borrowers are getting 1% exclusive listing fees on their next sale. [Learn more here.]</em><br><br>If you have any questions about the program or need additional info, please reach out directly to Suzanne or Paul:<br><br><strong>Suzanne Seini</strong><br>Innovate Realty<br>suzanne@innovaterealty.com<br><em>— OR —</em><br><strong>Paul Hanson</strong><br>phanson@byebyehouse.com"}
    make new to recipient at newMessage with properties {email address:{address:"jwiedman@centerstreetlending.com"}}
    open newMessage
    

    set newMessage to make new outgoing message with properties {subject:"CSL Resale Advantage – Your Custom Referral Link", content:"Hey Justin,<br><br>Check out the new website here: <a href=\"https://www.centerstreetlending.com/resale-advantage\">https://www.centerstreetlending.com/resale-advantage</a><br>Thanks for joining the information session this week on the new CSL Resale Advantage program!<br><br>Below is your custom link to send to your borrowers:<br><br><strong><a href=\"https://www.centerstreetlending.com/resale-advantage?rep=jwollm\">https://www.centerstreetlending.com/resale-advantage?rep=jwollm</a></strong><br><br>When a borrower uses your link, your information is automatically pushed through the form and marked in the system. As a backup, we can also always confirm you are the referral by communicating directly with Innovate Realty.<br><br><strong>If you'd like to make a custom email signature with your URL, feel free to add it into your Signature block to get evergreen marketing for your referral link.</strong><br><br><em>Example: Find out how CSL borrowers are getting 1% exclusive listing fees on their next sale. [Learn more here.]</em><br><br>If you have any questions about the program or need additional info, please reach out directly to Suzanne or Paul:<br><br><strong>Suzanne Seini</strong><br>Innovate Realty<br>suzanne@innovaterealty.com<br><em>— OR —</em><br><strong>Paul Hanson</strong><br>phanson@byebyehouse.com"}
    make new to recipient at newMessage with properties {email address:{address:"jwollm@centerstreetlending.com"}}
    open newMessage
    

    set newMessage to make new outgoing message with properties {subject:"CSL Resale Advantage – Your Custom Referral Link", content:"Hey Ryan,<br><br>Check out the new website here: <a href=\"https://www.centerstreetlending.com/resale-advantage\">https://www.centerstreetlending.com/resale-advantage</a><br>Thanks for joining the information session this week on the new CSL Resale Advantage program!<br><br>Below is your custom link to send to your borrowers:<br><br><strong><a href=\"https://www.centerstreetlending.com/resale-advantage?rep=rstjohn\">https://www.centerstreetlending.com/resale-advantage?rep=rstjohn</a></strong><br><br>When a borrower uses your link, your information is automatically pushed through the form and marked in the system. As a backup, we can also always confirm you are the referral by communicating directly with Innovate Realty.<br><br><strong>If you'd like to make a custom email signature with your URL, feel free to add it into your Signature block to get evergreen marketing for your referral link.</strong><br><br><em>Example: Find out how CSL borrowers are getting 1% exclusive listing fees on their next sale. [Learn more here.]</em><br><br>If you have any questions about the program or need additional info, please reach out directly to Suzanne or Paul:<br><br><strong>Suzanne Seini</strong><br>Innovate Realty<br>suzanne@innovaterealty.com<br><em>— OR —</em><br><strong>Paul Hanson</strong><br>phanson@byebyehouse.com"}
    make new to recipient at newMessage with properties {email address:{address:"rstjohn@centerstreetlending.com"}}
    open newMessage
    

    set newMessage to make new outgoing message with properties {subject:"CSL Resale Advantage – Your Custom Referral Link", content:"Hey Tanner,<br><br>Check out the new website here: <a href=\"https://www.centerstreetlending.com/resale-advantage\">https://www.centerstreetlending.com/resale-advantage</a><br>Thanks for joining the information session this week on the new CSL Resale Advantage program!<br><br>Below is your custom link to send to your borrowers:<br><br><strong><a href=\"https://www.centerstreetlending.com/resale-advantage?rep=tpodres\">https://www.centerstreetlending.com/resale-advantage?rep=tpodres</a></strong><br><br>When a borrower uses your link, your information is automatically pushed through the form and marked in the system. As a backup, we can also always confirm you are the referral by communicating directly with Innovate Realty.<br><br><strong>If you'd like to make a custom email signature with your URL, feel free to add it into your Signature block to get evergreen marketing for your referral link.</strong><br><br><em>Example: Find out how CSL borrowers are getting 1% exclusive listing fees on their next sale. [Learn more here.]</em><br><br>If you have any questions about the program or need additional info, please reach out directly to Suzanne or Paul:<br><br><strong>Suzanne Seini</strong><br>Innovate Realty<br>suzanne@innovaterealty.com<br><em>— OR —</em><br><strong>Paul Hanson</strong><br>phanson@byebyehouse.com"}
    make new to recipient at newMessage with properties {email address:{address:"tpodres@centerstreetlending.com"}}
    open newMessage
    

    set newMessage to make new outgoing message with properties {subject:"CSL Resale Advantage – Your Custom Referral Link", content:"Hey Angie,<br><br>Check out the new website here: <a href=\"https://www.centerstreetlending.com/resale-advantage\">https://www.centerstreetlending.com/resale-advantage</a><br>Thanks for joining the information session this week on the new CSL Resale Advantage program!<br><br>Below is your custom link to send to your borrowers:<br><br><strong><a href=\"https://www.centerstreetlending.com/resale-advantage?rep=aallen\">https://www.centerstreetlending.com/resale-advantage?rep=aallen</a></strong><br><br>When a borrower uses your link, your information is automatically pushed through the form and marked in the system. As a backup, we can also always confirm you are the referral by communicating directly with Innovate Realty.<br><br><strong>If you'd like to make a custom email signature with your URL, feel free to add it into your Signature block to get evergreen marketing for your referral link.</strong><br><br><em>Example: Find out how CSL borrowers are getting 1% exclusive listing fees on their next sale. [Learn more here.]</em><br><br>If you have any questions about the program or need additional info, please reach out directly to Suzanne or Paul:<br><br><strong>Suzanne Seini</strong><br>Innovate Realty<br>suzanne@innovaterealty.com<br><em>— OR —</em><br><strong>Paul Hanson</strong><br>phanson@byebyehouse.com"}
    make new to recipient at newMessage with properties {email address:{address:"aallen@centerstreetlending.com"}}
    open newMessage
    

    set newMessage to make new outgoing message with properties {subject:"CSL Resale Advantage – Your Custom Referral Link", content:"Hey Austin,<br><br>Check out the new website here: <a href=\"https://www.centerstreetlending.com/resale-advantage\">https://www.centerstreetlending.com/resale-advantage</a><br>Thanks for joining the information session this week on the new CSL Resale Advantage program!<br><br>Below is your custom link to send to your borrowers:<br><br><strong><a href=\"https://www.centerstreetlending.com/resale-advantage?rep=asteedman\">https://www.centerstreetlending.com/resale-advantage?rep=asteedman</a></strong><br><br>When a borrower uses your link, your information is automatically pushed through the form and marked in the system. As a backup, we can also always confirm you are the referral by communicating directly with Innovate Realty.<br><br><strong>If you'd like to make a custom email signature with your URL, feel free to add it into your Signature block to get evergreen marketing for your referral link.</strong><br><br><em>Example: Find out how CSL borrowers are getting 1% exclusive listing fees on their next sale. [Learn more here.]</em><br><br>If you have any questions about the program or need additional info, please reach out directly to Suzanne or Paul:<br><br><strong>Suzanne Seini</strong><br>Innovate Realty<br>suzanne@innovaterealty.com<br><em>— OR —</em><br><strong>Paul Hanson</strong><br>phanson@byebyehouse.com"}
    make new to recipient at newMessage with properties {email address:{address:"asteedman@centerstreetlending.com"}}
    open newMessage
    

    set newMessage to make new outgoing message with properties {subject:"CSL Resale Advantage – Your Custom Referral Link", content:"Hey Kara,<br><br>Check out the new website here: <a href=\"https://www.centerstreetlending.com/resale-advantage\">https://www.centerstreetlending.com/resale-advantage</a><br>Thanks for joining the information session this week on the new CSL Resale Advantage program!<br><br>Below is your custom link to send to your borrowers:<br><br><strong><a href=\"https://www.centerstreetlending.com/resale-advantage?rep=karmstrong\">https://www.centerstreetlending.com/resale-advantage?rep=karmstrong</a></strong><br><br>When a borrower uses your link, your information is automatically pushed through the form and marked in the system. As a backup, we can also always confirm you are the referral by communicating directly with Innovate Realty.<br><br><strong>If you'd like to make a custom email signature with your URL, feel free to add it into your Signature block to get evergreen marketing for your referral link.</strong><br><br><em>Example: Find out how CSL borrowers are getting 1% exclusive listing fees on their next sale. [Learn more here.]</em><br><br>If you have any questions about the program or need additional info, please reach out directly to Suzanne or Paul:<br><br><strong>Suzanne Seini</strong><br>Innovate Realty<br>suzanne@innovaterealty.com<br><em>— OR —</em><br><strong>Paul Hanson</strong><br>phanson@byebyehouse.com"}
    make new to recipient at newMessage with properties {email address:{address:"karmstrong@centerstreetlending.com"}}
    open newMessage
    

    set newMessage to make new outgoing message with properties {subject:"CSL Resale Advantage – Your Custom Referral Link", content:"Hey Max,<br><br>Check out the new website here: <a href=\"https://www.centerstreetlending.com/resale-advantage\">https://www.centerstreetlending.com/resale-advantage</a><br>Thanks for joining the information session this week on the new CSL Resale Advantage program!<br><br>Below is your custom link to send to your borrowers:<br><br><strong><a href=\"https://www.centerstreetlending.com/resale-advantage?rep=mwoodyard\">https://www.centerstreetlending.com/resale-advantage?rep=mwoodyard</a></strong><br><br>When a borrower uses your link, your information is automatically pushed through the form and marked in the system. As a backup, we can also always confirm you are the referral by communicating directly with Innovate Realty.<br><br><strong>If you'd like to make a custom email signature with your URL, feel free to add it into your Signature block to get evergreen marketing for your referral link.</strong><br><br><em>Example: Find out how CSL borrowers are getting 1% exclusive listing fees on their next sale. [Learn more here.]</em><br><br>If you have any questions about the program or need additional info, please reach out directly to Suzanne or Paul:<br><br><strong>Suzanne Seini</strong><br>Innovate Realty<br>suzanne@innovaterealty.com<br><em>— OR —</em><br><strong>Paul Hanson</strong><br>phanson@byebyehouse.com"}
    make new to recipient at newMessage with properties {email address:{address:"mwoodyard@centerstreetlending.com"}}
    open newMessage
    

    set newMessage to make new outgoing message with properties {subject:"CSL Resale Advantage – Your Custom Referral Link", content:"Hey Michael,<br><br>Check out the new website here: <a href=\"https://www.centerstreetlending.com/resale-advantage\">https://www.centerstreetlending.com/resale-advantage</a><br>Thanks for joining the information session this week on the new CSL Resale Advantage program!<br><br>Below is your custom link to send to your borrowers:<br><br><strong><a href=\"https://www.centerstreetlending.com/resale-advantage?rep=mprice\">https://www.centerstreetlending.com/resale-advantage?rep=mprice</a></strong><br><br>When a borrower uses your link, your information is automatically pushed through the form and marked in the system. As a backup, we can also always confirm you are the referral by communicating directly with Innovate Realty.<br><br><strong>If you'd like to make a custom email signature with your URL, feel free to add it into your Signature block to get evergreen marketing for your referral link.</strong><br><br><em>Example: Find out how CSL borrowers are getting 1% exclusive listing fees on their next sale. [Learn more here.]</em><br><br>If you have any questions about the program or need additional info, please reach out directly to Suzanne or Paul:<br><br><strong>Suzanne Seini</strong><br>Innovate Realty<br>suzanne@innovaterealty.com<br><em>— OR —</em><br><strong>Paul Hanson</strong><br>phanson@byebyehouse.com"}
    make new to recipient at newMessage with properties {email address:{address:"mprice@centerstreetlending.com"}}
    open newMessage
    

    set newMessage to make new outgoing message with properties {subject:"CSL Resale Advantage – Your Custom Referral Link", content:"Hey Robert,<br><br>Check out the new website here: <a href=\"https://www.centerstreetlending.com/resale-advantage\">https://www.centerstreetlending.com/resale-advantage</a><br>Thanks for joining the information session this week on the new CSL Resale Advantage program!<br><br>Below is your custom link to send to your borrowers:<br><br><strong><a href=\"https://www.centerstreetlending.com/resale-advantage?rep=rnewcomer\">https://www.centerstreetlending.com/resale-advantage?rep=rnewcomer</a></strong><br><br>When a borrower uses your link, your information is automatically pushed through the form and marked in the system. As a backup, we can also always confirm you are the referral by communicating directly with Innovate Realty.<br><br><strong>If you'd like to make a custom email signature with your URL, feel free to add it into your Signature block to get evergreen marketing for your referral link.</strong><br><br><em>Example: Find out how CSL borrowers are getting 1% exclusive listing fees on their next sale. [Learn more here.]</em><br><br>If you have any questions about the program or need additional info, please reach out directly to Suzanne or Paul:<br><br><strong>Suzanne Seini</strong><br>Innovate Realty<br>suzanne@innovaterealty.com<br><em>— OR —</em><br><strong>Paul Hanson</strong><br>phanson@byebyehouse.com"}
    make new to recipient at newMessage with properties {email address:{address:"rnewcomer@centerstreetlending.com"}}
    open newMessage
    

    set newMessage to make new outgoing message with properties {subject:"CSL Resale Advantage – Your Custom Referral Link", content:"Hey Sean,<br><br>Check out the new website here: <a href=\"https://www.centerstreetlending.com/resale-advantage\">https://www.centerstreetlending.com/resale-advantage</a><br>Thanks for joining the information session this week on the new CSL Resale Advantage program!<br><br>Below is your custom link to send to your borrowers:<br><br><strong><a href=\"https://www.centerstreetlending.com/resale-advantage?rep=sburbidge\">https://www.centerstreetlending.com/resale-advantage?rep=sburbidge</a></strong><br><br>When a borrower uses your link, your information is automatically pushed through the form and marked in the system. As a backup, we can also always confirm you are the referral by communicating directly with Innovate Realty.<br><br><strong>If you'd like to make a custom email signature with your URL, feel free to add it into your Signature block to get evergreen marketing for your referral link.</strong><br><br><em>Example: Find out how CSL borrowers are getting 1% exclusive listing fees on their next sale. [Learn more here.]</em><br><br>If you have any questions about the program or need additional info, please reach out directly to Suzanne or Paul:<br><br><strong>Suzanne Seini</strong><br>Innovate Realty<br>suzanne@innovaterealty.com<br><em>— OR —</em><br><strong>Paul Hanson</strong><br>phanson@byebyehouse.com"}
    make new to recipient at newMessage with properties {email address:{address:"sburbidge@centerstreetlending.com"}}
    open newMessage
    

    set newMessage to make new outgoing message with properties {subject:"CSL Resale Advantage – Your Custom Referral Link", content:"Hey Dallin,<br><br>Check out the new website here: <a href=\"https://www.centerstreetlending.com/resale-advantage\">https://www.centerstreetlending.com/resale-advantage</a><br>Thanks for joining the information session this week on the new CSL Resale Advantage program!<br><br>Below is your custom link to send to your borrowers:<br><br><strong><a href=\"https://www.centerstreetlending.com/resale-advantage?rep=dwaldvogel\">https://www.centerstreetlending.com/resale-advantage?rep=dwaldvogel</a></strong><br><br>When a borrower uses your link, your information is automatically pushed through the form and marked in the system. As a backup, we can also always confirm you are the referral by communicating directly with Innovate Realty.<br><br><strong>If you'd like to make a custom email signature with your URL, feel free to add it into your Signature block to get evergreen marketing for your referral link.</strong><br><br><em>Example: Find out how CSL borrowers are getting 1% exclusive listing fees on their next sale. [Learn more here.]</em><br><br>If you have any questions about the program or need additional info, please reach out directly to Suzanne or Paul:<br><br><strong>Suzanne Seini</strong><br>Innovate Realty<br>suzanne@innovaterealty.com<br><em>— OR —</em><br><strong>Paul Hanson</strong><br>phanson@byebyehouse.com"}
    make new to recipient at newMessage with properties {email address:{address:"dwaldvogel@centerstreetlending.com"}}
    open newMessage
    

    set newMessage to make new outgoing message with properties {subject:"CSL Resale Advantage – Your Custom Referral Link", content:"Hey Ford,<br><br>Check out the new website here: <a href=\"https://www.centerstreetlending.com/resale-advantage\">https://www.centerstreetlending.com/resale-advantage</a><br>Thanks for joining the information session this week on the new CSL Resale Advantage program!<br><br>Below is your custom link to send to your borrowers:<br><br><strong><a href=\"https://www.centerstreetlending.com/resale-advantage?rep=ffairon\">https://www.centerstreetlending.com/resale-advantage?rep=ffairon</a></strong><br><br>When a borrower uses your link, your information is automatically pushed through the form and marked in the system. As a backup, we can also always confirm you are the referral by communicating directly with Innovate Realty.<br><br><strong>If you'd like to make a custom email signature with your URL, feel free to add it into your Signature block to get evergreen marketing for your referral link.</strong><br><br><em>Example: Find out how CSL borrowers are getting 1% exclusive listing fees on their next sale. [Learn more here.]</em><br><br>If you have any questions about the program or need additional info, please reach out directly to Suzanne or Paul:<br><br><strong>Suzanne Seini</strong><br>Innovate Realty<br>suzanne@innovaterealty.com<br><em>— OR —</em><br><strong>Paul Hanson</strong><br>phanson@byebyehouse.com"}
    make new to recipient at newMessage with properties {email address:{address:"ffairon@centerstreetlending.com"}}
    open newMessage
    

    set newMessage to make new outgoing message with properties {subject:"CSL Resale Advantage – Your Custom Referral Link", content:"Hey Guy,<br><br>Check out the new website here: <a href=\"https://www.centerstreetlending.com/resale-advantage\">https://www.centerstreetlending.com/resale-advantage</a><br>Thanks for joining the information session this week on the new CSL Resale Advantage program!<br><br>Below is your custom link to send to your borrowers:<br><br><strong><a href=\"https://www.centerstreetlending.com/resale-advantage?rep=gclauss\">https://www.centerstreetlending.com/resale-advantage?rep=gclauss</a></strong><br><br>When a borrower uses your link, your information is automatically pushed through the form and marked in the system. As a backup, we can also always confirm you are the referral by communicating directly with Innovate Realty.<br><br><strong>If you'd like to make a custom email signature with your URL, feel free to add it into your Signature block to get evergreen marketing for your referral link.</strong><br><br><em>Example: Find out how CSL borrowers are getting 1% exclusive listing fees on their next sale. [Learn more here.]</em><br><br>If you have any questions about the program or need additional info, please reach out directly to Suzanne or Paul:<br><br><strong>Suzanne Seini</strong><br>Innovate Realty<br>suzanne@innovaterealty.com<br><em>— OR —</em><br><strong>Paul Hanson</strong><br>phanson@byebyehouse.com"}
    make new to recipient at newMessage with properties {email address:{address:"gclauss@centerstreetlending.com"}}
    open newMessage
    

    set newMessage to make new outgoing message with properties {subject:"CSL Resale Advantage – Your Custom Referral Link", content:"Hey Jack,<br><br>Check out the new website here: <a href=\"https://www.centerstreetlending.com/resale-advantage\">https://www.centerstreetlending.com/resale-advantage</a><br>Thanks for joining the information session this week on the new CSL Resale Advantage program!<br><br>Below is your custom link to send to your borrowers:<br><br><strong><a href=\"https://www.centerstreetlending.com/resale-advantage?rep=jguenther\">https://www.centerstreetlending.com/resale-advantage?rep=jguenther</a></strong><br><br>When a borrower uses your link, your information is automatically pushed through the form and marked in the system. As a backup, we can also always confirm you are the referral by communicating directly with Innovate Realty.<br><br><strong>If you'd like to make a custom email signature with your URL, feel free to add it into your Signature block to get evergreen marketing for your referral link.</strong><br><br><em>Example: Find out how CSL borrowers are getting 1% exclusive listing fees on their next sale. [Learn more here.]</em><br><br>If you have any questions about the program or need additional info, please reach out directly to Suzanne or Paul:<br><br><strong>Suzanne Seini</strong><br>Innovate Realty<br>suzanne@innovaterealty.com<br><em>— OR —</em><br><strong>Paul Hanson</strong><br>phanson@byebyehouse.com"}
    make new to recipient at newMessage with properties {email address:{address:"jguenther@centerstreetlending.com"}}
    open newMessage
    

    set newMessage to make new outgoing message with properties {subject:"CSL Resale Advantage – Your Custom Referral Link", content:"Hey Ryan,<br><br>Check out the new website here: <a href=\"https://www.centerstreetlending.com/resale-advantage\">https://www.centerstreetlending.com/resale-advantage</a><br>Thanks for joining the information session this week on the new CSL Resale Advantage program!<br><br>Below is your custom link to send to your borrowers:<br><br><strong><a href=\"https://www.centerstreetlending.com/resale-advantage?rep=rclayton\">https://www.centerstreetlending.com/resale-advantage?rep=rclayton</a></strong><br><br>When a borrower uses your link, your information is automatically pushed through the form and marked in the system. As a backup, we can also always confirm you are the referral by communicating directly with Innovate Realty.<br><br><strong>If you'd like to make a custom email signature with your URL, feel free to add it into your Signature block to get evergreen marketing for your referral link.</strong><br><br><em>Example: Find out how CSL borrowers are getting 1% exclusive listing fees on their next sale. [Learn more here.]</em><br><br>If you have any questions about the program or need additional info, please reach out directly to Suzanne or Paul:<br><br><strong>Suzanne Seini</strong><br>Innovate Realty<br>suzanne@innovaterealty.com<br><em>— OR —</em><br><strong>Paul Hanson</strong><br>phanson@byebyehouse.com"}
    make new to recipient at newMessage with properties {email address:{address:"rclayton@centerstreetlending.com"}}
    open newMessage
    

    set newMessage to make new outgoing message with properties {subject:"CSL Resale Advantage – Your Custom Referral Link", content:"Hey Sean,<br><br>Check out the new website here: <a href=\"https://www.centerstreetlending.com/resale-advantage\">https://www.centerstreetlending.com/resale-advantage</a><br>Thanks for joining the information session this week on the new CSL Resale Advantage program!<br><br>Below is your custom link to send to your borrowers:<br><br><strong><a href=\"https://www.centerstreetlending.com/resale-advantage?rep=sklement\">https://www.centerstreetlending.com/resale-advantage?rep=sklement</a></strong><br><br>When a borrower uses your link, your information is automatically pushed through the form and marked in the system. As a backup, we can also always confirm you are the referral by communicating directly with Innovate Realty.<br><br><strong>If you'd like to make a custom email signature with your URL, feel free to add it into your Signature block to get evergreen marketing for your referral link.</strong><br><br><em>Example: Find out how CSL borrowers are getting 1% exclusive listing fees on their next sale. [Learn more here.]</em><br><br>If you have any questions about the program or need additional info, please reach out directly to Suzanne or Paul:<br><br><strong>Suzanne Seini</strong><br>Innovate Realty<br>suzanne@innovaterealty.com<br><em>— OR —</em><br><strong>Paul Hanson</strong><br>phanson@byebyehouse.com"}
    make new to recipient at newMessage with properties {email address:{address:"sklement@centerstreetlending.com"}}
    open newMessage
    

    set newMessage to make new outgoing message with properties {subject:"CSL Resale Advantage – Your Custom Referral Link", content:"Hey Brandon,<br><br>Check out the new website here: <a href=\"https://www.centerstreetlending.com/resale-advantage\">https://www.centerstreetlending.com/resale-advantage</a><br>Thanks for joining the information session this week on the new CSL Resale Advantage program!<br><br>Below is your custom link to send to your borrowers:<br><br><strong><a href=\"https://www.centerstreetlending.com/resale-advantage?rep=bherbert\">https://www.centerstreetlending.com/resale-advantage?rep=bherbert</a></strong><br><br>When a borrower uses your link, your information is automatically pushed through the form and marked in the system. As a backup, we can also always confirm you are the referral by communicating directly with Innovate Realty.<br><br><strong>If you'd like to make a custom email signature with your URL, feel free to add it into your Signature block to get evergreen marketing for your referral link.</strong><br><br><em>Example: Find out how CSL borrowers are getting 1% exclusive listing fees on their next sale. [Learn more here.]</em><br><br>If you have any questions about the program or need additional info, please reach out directly to Suzanne or Paul:<br><br><strong>Suzanne Seini</strong><br>Innovate Realty<br>suzanne@innovaterealty.com<br><em>— OR —</em><br><strong>Paul Hanson</strong><br>phanson@byebyehouse.com"}
    make new to recipient at newMessage with properties {email address:{address:"bherbert@centerstreetlending.com"}}
    open newMessage
    

    set newMessage to make new outgoing message with properties {subject:"CSL Resale Advantage – Your Custom Referral Link", content:"Hey Crystal,<br><br>Check out the new website here: <a href=\"https://www.centerstreetlending.com/resale-advantage\">https://www.centerstreetlending.com/resale-advantage</a><br>Thanks for joining the information session this week on the new CSL Resale Advantage program!<br><br>Below is your custom link to send to your borrowers:<br><br><strong><a href=\"https://www.centerstreetlending.com/resale-advantage?rep=cmora\">https://www.centerstreetlending.com/resale-advantage?rep=cmora</a></strong><br><br>When a borrower uses your link, your information is automatically pushed through the form and marked in the system. As a backup, we can also always confirm you are the referral by communicating directly with Innovate Realty.<br><br><strong>If you'd like to make a custom email signature with your URL, feel free to add it into your Signature block to get evergreen marketing for your referral link.</strong><br><br><em>Example: Find out how CSL borrowers are getting 1% exclusive listing fees on their next sale. [Learn more here.]</em><br><br>If you have any questions about the program or need additional info, please reach out directly to Suzanne or Paul:<br><br><strong>Suzanne Seini</strong><br>Innovate Realty<br>suzanne@innovaterealty.com<br><em>— OR —</em><br><strong>Paul Hanson</strong><br>phanson@byebyehouse.com"}
    make new to recipient at newMessage with properties {email address:{address:"cmora@centerstreetlending.com"}}
    open newMessage
    

    set newMessage to make new outgoing message with properties {subject:"CSL Resale Advantage – Your Custom Referral Link", content:"Hey Jacob,<br><br>Check out the new website here: <a href=\"https://www.centerstreetlending.com/resale-advantage\">https://www.centerstreetlending.com/resale-advantage</a><br>Thanks for joining the information session this week on the new CSL Resale Advantage program!<br><br>Below is your custom link to send to your borrowers:<br><br><strong><a href=\"https://www.centerstreetlending.com/resale-advantage?rep=jwoodyard\">https://www.centerstreetlending.com/resale-advantage?rep=jwoodyard</a></strong><br><br>When a borrower uses your link, your information is automatically pushed through the form and marked in the system. As a backup, we can also always confirm you are the referral by communicating directly with Innovate Realty.<br><br><strong>If you'd like to make a custom email signature with your URL, feel free to add it into your Signature block to get evergreen marketing for your referral link.</strong><br><br><em>Example: Find out how CSL borrowers are getting 1% exclusive listing fees on their next sale. [Learn more here.]</em><br><br>If you have any questions about the program or need additional info, please reach out directly to Suzanne or Paul:<br><br><strong>Suzanne Seini</strong><br>Innovate Realty<br>suzanne@innovaterealty.com<br><em>— OR —</em><br><strong>Paul Hanson</strong><br>phanson@byebyehouse.com"}
    make new to recipient at newMessage with properties {email address:{address:"jwoodyard@centerstreetlending.com"}}
    open newMessage
    

    set newMessage to make new outgoing message with properties {subject:"CSL Resale Advantage – Your Custom Referral Link", content:"Hey Lauren,<br><br>Check out the new website here: <a href=\"https://www.centerstreetlending.com/resale-advantage\">https://www.centerstreetlending.com/resale-advantage</a><br>Thanks for joining the information session this week on the new CSL Resale Advantage program!<br><br>Below is your custom link to send to your borrowers:<br><br><strong><a href=\"https://www.centerstreetlending.com/resale-advantage?rep=llipinski\">https://www.centerstreetlending.com/resale-advantage?rep=llipinski</a></strong><br><br>When a borrower uses your link, your information is automatically pushed through the form and marked in the system. As a backup, we can also always confirm you are the referral by communicating directly with Innovate Realty.<br><br><strong>If you'd like to make a custom email signature with your URL, feel free to add it into your Signature block to get evergreen marketing for your referral link.</strong><br><br><em>Example: Find out how CSL borrowers are getting 1% exclusive listing fees on their next sale. [Learn more here.]</em><br><br>If you have any questions about the program or need additional info, please reach out directly to Suzanne or Paul:<br><br><strong>Suzanne Seini</strong><br>Innovate Realty<br>suzanne@innovaterealty.com<br><em>— OR —</em><br><strong>Paul Hanson</strong><br>phanson@byebyehouse.com"}
    make new to recipient at newMessage with properties {email address:{address:"llipinski@centerstreetlending.com"}}
    open newMessage
    

    set newMessage to make new outgoing message with properties {subject:"CSL Resale Advantage – Your Custom Referral Link", content:"Hey Richard,<br><br>Check out the new website here: <a href=\"https://www.centerstreetlending.com/resale-advantage\">https://www.centerstreetlending.com/resale-advantage</a><br>Thanks for joining the information session this week on the new CSL Resale Advantage program!<br><br>Below is your custom link to send to your borrowers:<br><br><strong><a href=\"https://www.centerstreetlending.com/resale-advantage?rep=rkim\">https://www.centerstreetlending.com/resale-advantage?rep=rkim</a></strong><br><br>When a borrower uses your link, your information is automatically pushed through the form and marked in the system. As a backup, we can also always confirm you are the referral by communicating directly with Innovate Realty.<br><br><strong>If you'd like to make a custom email signature with your URL, feel free to add it into your Signature block to get evergreen marketing for your referral link.</strong><br><br><em>Example: Find out how CSL borrowers are getting 1% exclusive listing fees on their next sale. [Learn more here.]</em><br><br>If you have any questions about the program or need additional info, please reach out directly to Suzanne or Paul:<br><br><strong>Suzanne Seini</strong><br>Innovate Realty<br>suzanne@innovaterealty.com<br><em>— OR —</em><br><strong>Paul Hanson</strong><br>phanson@byebyehouse.com"}
    make new to recipient at newMessage with properties {email address:{address:"rkim@centerstreetlending.com"}}
    open newMessage
    

    set newMessage to make new outgoing message with properties {subject:"CSL Resale Advantage – Your Custom Referral Link", content:"Hey Trevor,<br><br>Check out the new website here: <a href=\"https://www.centerstreetlending.com/resale-advantage\">https://www.centerstreetlending.com/resale-advantage</a><br>Thanks for joining the information session this week on the new CSL Resale Advantage program!<br><br>Below is your custom link to send to your borrowers:<br><br><strong><a href=\"https://www.centerstreetlending.com/resale-advantage?rep=tburbidge\">https://www.centerstreetlending.com/resale-advantage?rep=tburbidge</a></strong><br><br>When a borrower uses your link, your information is automatically pushed through the form and marked in the system. As a backup, we can also always confirm you are the referral by communicating directly with Innovate Realty.<br><br><strong>If you'd like to make a custom email signature with your URL, feel free to add it into your Signature block to get evergreen marketing for your referral link.</strong><br><br><em>Example: Find out how CSL borrowers are getting 1% exclusive listing fees on their next sale. [Learn more here.]</em><br><br>If you have any questions about the program or need additional info, please reach out directly to Suzanne or Paul:<br><br><strong>Suzanne Seini</strong><br>Innovate Realty<br>suzanne@innovaterealty.com<br><em>— OR —</em><br><strong>Paul Hanson</strong><br>phanson@byebyehouse.com"}
    make new to recipient at newMessage with properties {email address:{address:"tburbidge@centerstreetlending.com"}}
    open newMessage
    

    set newMessage to make new outgoing message with properties {subject:"CSL Resale Advantage – Your Custom Referral Link", content:"Hey Jacob,<br><br>Check out the new website here: <a href=\"https://www.centerstreetlending.com/resale-advantage\">https://www.centerstreetlending.com/resale-advantage</a><br>Thanks for joining the information session this week on the new CSL Resale Advantage program!<br><br>Below is your custom link to send to your borrowers:<br><br><strong><a href=\"https://www.centerstreetlending.com/resale-advantage?rep=jcho\">https://www.centerstreetlending.com/resale-advantage?rep=jcho</a></strong><br><br>When a borrower uses your link, your information is automatically pushed through the form and marked in the system. As a backup, we can also always confirm you are the referral by communicating directly with Innovate Realty.<br><br><strong>If you'd like to make a custom email signature with your URL, feel free to add it into your Signature block to get evergreen marketing for your referral link.</strong><br><br><em>Example: Find out how CSL borrowers are getting 1% exclusive listing fees on their next sale. [Learn more here.]</em><br><br>If you have any questions about the program or need additional info, please reach out directly to Suzanne or Paul:<br><br><strong>Suzanne Seini</strong><br>Innovate Realty<br>suzanne@innovaterealty.com<br><em>— OR —</em><br><strong>Paul Hanson</strong><br>phanson@byebyehouse.com"}
    make new to recipient at newMessage with properties {email address:{address:"jcho@centerstreetlending.com"}}
    open newMessage
    
end tell